### ISSUE TITLE
Areas of city

### ISSUE THREAD

**Issue by Umar431497** [dr5hn/countries-states-cities-database#100]
I want to fetch the areas in a city as well

**Comment by dr5hn** [comment]
@Umar431497 Thanks for your suggestion.

Good to have. But difficult to incorporate at the moment.

**Comment by Umar431497** [comment]
@dr5hn Any other source or link .. I need to add these in my project
or how many days will it take to add towns of cities

**Comment by dr5hn** [comment]
@Umar431497 I did some research on this long back. also forgotten the name of sources.

But data was very scattered at different sources. It requires a lot of manual efforts to bring them together.

**Comment by dr5hn** [comment]
@Umar431497 Closing for now.
