### ISSUE TITLE
Cities are repeated with district, city or province suffix

### ISSUE THREAD

**Issue by sryn101** [dr5hn/countries-states-cities-database#103]
Hi, I must admit you are doing a great job.. just found some discrepancies.. 

There are duplicates of the same city with district, city, county or province suffix. 
Eg., 
City ID 131457 and 131458 Kwekwe  and Kwekwe District respectively.. both are same
City ID 117601 and 117602 Green Lake and Green Lake County respectively.. both are same 

Similarly there are plenty of other records with province, city etc.,

**Comment by dr5hn** [comment]
@sryn101 Thanks for reporting. 🎉 I will take a look at it ASAP.

**Comment by sryn101** [comment]
Thanks for your swift response @dr5hn  I just made a list of all strings to look for while identifying duplicates: 

COUNTY
PROVINCE OF
CITY OF
GOVERNADOR
MUNICIPIO
RAYON
KOMMUN
DEVELOPMENT BLOCK
CITY PROVINCE
CITY MUNICIPALITY
CITY MUNICIPALITY OF
CANTON OF
DISTRICT MUNICIPALITY
METROPOLITAN REGION
MUNICIPALITY OF
REGION
STATE
VOIVODESHIP
VILLAGE
VICEROYALTY
TOWNSHIP
TOWN
SUBPREFECTURE
SUBDISTRICT
STATE
RURAL DISTRICT
REGION
PROVINCE
PREFECTURE
PARISH
MUNICIPALITY
METROPOLITAN
HUNDRED
GOVERNORATE
FEDERATIVE
FEDERAL STATE
EMIRATE
DUCHY
DISTRICT
DEPARTMENT
COUNTY
CONSTITUENT
COMMUNE
CITY
CANTON
BOROUGH
BAILIWICK

Hope this helps :)

**Comment by Pakeydev** [comment]
Hi,

In Readme.md it stated that;

Insights
Total Countries : 248
Total States/Regions/Municipalities : 4,872
Total Cities/Towns/Districts : 141,850

But when upload it to my phpMyAdmin total cities is 142842. Is this mean there is 992 duplicated cities or is it the Insight not updated with new total cities?

Thanks.

**Comment by dr5hn** [comment]
@Pakeydev Insights are not updated.

**Comment by dr5hn** [comment]
Closing this as it is being solved chunk by chunk.
