### ISSUE TITLE
Ahmedabad/Ahmadabad bug

### ISSUE THREAD

**Issue by aastashov** [dr5hn/countries-states-cities-database#104]
Thank you for creating this repository!

Ahmedabad (id=67606) and Ahmadabad (id=67605) are the same city with different names. I don't know exactly, but according to wikipedia and maps.google.com, it will be correct to use Ahmedabad. So Ahmadabad needs to be removed.

https://en.wikipedia.org/wiki/Ahmedabad
https://www.google.com/maps/place/Ahmedabad,+Gujarat,+India/@23.0201818,72.4396587,11z/data=!3m1!4b1!4m5!3m4!1s0x395e848aba5bd449:0x4fcedd11614f6516!8m2!3d23.022505!4d72.5713621

**Comment by aastashov** [comment]
How can I help in promoting this question?

**Comment by dr5hn** [comment]
@aastashov Thanks for reporting. 🎉 Don't worry i will fix it ASAP.
