### ISSUE TITLE
Many Provinces in the Philippines have no cities

### ISSUE THREAD

**Issue by quezon** [dr5hn/countries-states-cities-database#107]
Provinces like Pangasinan have no cities with it. How to contribute and change data especially for Philippines?

**Comment by quezon** [comment]
Wikipedia has more accurate source of information
https://en.wikipedia.org/wiki/List_of_cities_and_municipalities_in_the_Philippines

**Comment by dr5hn** [comment]
ADD: #108 
Metro Manila, Philippines has a wrong set of cities/towns

**Comment by dr5hn** [comment]
@quezon Thanks for reporting. 🎉 

For contribution, you need to update sql files and raise a PR. Please take a look at [Contribution Guidelines](https://github.com/dr5hn/countries-states-cities-database/blob/master/CONTRIBUTING.md)

**Comment by karmakula** [comment]
Hi. i would love to help a fellow Filipino with this issue

**Comment by dr5hn** [comment]
@karmakula Feel free to contribute.

**Comment by dr5hn** [comment]
@quezon 

1. Fixed Manila Cities
2. Found Cities for Following Provinces
```
1270	Bukidnon
1272	Bohol
1278	Bulacan
1279	Cagayan
1283	Camarines Norte
1309	Davao Occidental
1323	Agusan del Norte
1326	Agusan del Sur
1324	Abra
```
Raised PR #107
