### ISSUE TITLE
Missing Lexington, Kentucky

### ISSUE THREAD

**Issue by Mottie** [dr5hn/countries-states-cities-database#11]
Pretty much every list of U.S. cities & states I've found on GitHub is missing [Lexington, Kentucky](https://goo.gl/maps/4SyoCAMBU822).

In your data base, the main data file https://github.com/dr5hn/countries-states-cities-database/blob/master/PHP_Scripts/data/us-cities.json#L335 needs to be updated. There's an empty string where Lexington should be listed:

```js
..."LEWISPORT", "", "LIBERTY",...
```

**Comment by dr5hn** [comment]
@Mottie Done. Added.
https://github.com/dr5hn/countries-states-cities-database/commit/fde09ad7d5e4ff2276c640f36aa38e3dd3928570

Thanks for heads up on that. Appreciate your efforts.
