### ISSUE TITLE
Nassau missing from states database under country bahamas

### ISSUE THREAD

**Issue by sirsweet242** [dr5hn/countries-states-cities-database#119]
INSERT INTO `hvisa_world_states`(`id`, `name`, `country_id`, `country_code`, `fips_code`, `iso2`, `created_at`, `updated_at`, `flag`, `wikiDataId`) VALUES ('4881','Nassau','17','BS','BF','NS','2020-10-10 17:45:55','2020-10-10 17:45:55','1','Q2467')
Nassau is mentioned in the country db as the capital under the country (bahamas) but not under the states db.

**Comment by dr5hn** [comment]
@sirsweet242 Thanks for reporting. 🎉 

According to Wikipedia, https://en.wikipedia.org/wiki/Nassau,_Bahamas
`Nassau` is the largest **CITY** of Bahamas, whereas it lies under **State** `New Providence`.

Hence i am adding 
- `New Providence` as a State
- `Nassau`as a City
