### ISSUE TITLE
Cities are missing in colombo and kandy District of Sri lanka

### ISSUE THREAD

**Issue by psmahantesh** [dr5hn/countries-states-cities-database#123]
FYI,

Kandy: https://en.wikipedia.org/wiki/Kandy_District

Colombo: https://en.wikipedia.org/wiki/Colombo_District

Kindly check and update missing cities asap

**Comment by dr5hn** [comment]
@psmahantesh Thanks for reporting 🎉  I will look into it.

**Comment by patrickdaze** [comment]
Looking into this one now
