### ISSUE TITLE
Continents and their countries

### ISSUE THREAD

**Issue by dereuromark** [dr5hn/countries-states-cities-database#125]
I have a DB with

> Continents => Countries => States => Counties => Districts => Cities

So basically quite similar, I could see if I can sync that.

My main question:
Would you also consider adding Countries to Continents grouping/linking?

Right now there is no fully complete list yet in the internet anywhere, and it could fit here quite well.
I have a list of 200/250 countries mapped here already to the continents.

![continents_and_countries](https://user-images.githubusercontent.com/39854/97029188-5eb51680-155d-11eb-9557-3e0259df5797.png)

Still missing like 45 then, and the lists in Wikipedia and CO are partially incomplete or problematic.
Would be nice to have it included in a high quality data set for easier contribution.

What do you think?

**Comment by dereuromark** [comment]
After I saw the other ticket, maybe I should also call them regions instead. That allows this more flexible separation or nesting of them.

**Comment by dr5hn** [comment]
@dereuromark Thanks for putting this up. Appreciate your help. 🎉 

This addition was already there on my To-Do List. I am happy to have it.

I would like to have it included this way: [API](https://restcountries.eu/rest/v2/all?fields=name;region;subregion)
```diff
{
  "id": 101,
  "name": "India",
  "iso3": "IND",
  "iso2": "IN",
  "phone_code": "91",
  "capital": "New Delhi",
  "currency": "INR",
  "native": "भारत",
  "emoji": "🇮🇳",
  "emojiU": "U+1F1EE U+1F1F3",
+ "region": "Asia",
+ "subregion": "Southern Asia"
}
```

#101 I would also like to add many things to DB like:
- [Timezone Abbreviations & Offsets](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations)
- [Languages](https://restcountries.eu/rest/v2/all?fields=name;languages)

Let me know if you need anything from me.

**Comment by dereuromark** [comment]
If you include from that source I would recommend matching not on the human name, but the alpha3Code:
https://restcountries.eu/rest/v2/all?fields=name;alpha3Code;region;subregion

This way, even if they or this db changes a name of a country slightly (e vs é etc), it would still match fine.
Country names can change, their iso code usually not.

**Comment by dr5hn** [comment]
@dereuromark Done. Added.

The only difference I see between your region screenshot and this API is of wordings.
```
North America
Northern Americas
```
Do you know which one is preferable?

Added one more missing country Curaçao 🇨🇼

All thanks go to you. 🎉

**Comment by dereuromark** [comment]
I dont mind either way
I guess the first is more common.

In the end I recommend using the codes for reading and comparing it, this way it isnt a big deal to match with other libs and data.
SA, NA, ...

**Comment by dr5hn** [comment]
@dereuromark 

Thanks for the confirmation.

I've already added these fields in countries, have you checked?
https://github.com/dr5hn/countries-states-cities-database/pull/128/files
