### ISSUE TITLE
Population per level

### ISSUE THREAD

**Issue by dereuromark** [dr5hn/countries-states-cities-database#132]
Are you also interested in containing population count (integer) per level?
- Country
- Region
- City

etc?

Here would be the German one for example for the larger ones (>=100.000):
[cities_population_DE.txt](https://github.com/dr5hn/countries-states-cities-database/files/5452457/cities_population_DE.txt)

I can understand that this might be a bit too much, especially since the data changes every year
And the ISO data usually shouldn't that often :)

**Comment by dr5hn** [comment]
@dereuromark Thanks for the suggestion, But It is very difficult to incorporate at the moment. and also I am actually interested in data that are more static in nature and changes less frequently or never.

**Comment by dereuromark** [comment]
Makes sense :)
