### ISSUE TITLE
Bonaire and Sint Maarten are missing from the database.

### ISSUE THREAD

**Issue by narayanmoni** [dr5hn/countries-states-cities-database#137]
The ISO 3166 standard has the following countries in it. But they are not in this database. 

1. Bonaire, Sint Eustatius and Saba
2. Sint Maarten

Is there a reason why? I can update the countries.sql and create a pull request to try and keep this DB compliant with the ISO standards.

**Comment by dr5hn** [comment]
@narayanmoni I need to check the 1st one but for sure 2nd one is already present.
```
  {
        "id": 190,
        "name": "Saint-Martin (French part)",
        "iso3": "MAF",
        "iso2": "MF",
        "phone_code": "590",
        "capital": "Marigot",
        "currency": "EUR",
        "native": "Saint-Martin",
        "region": "Americas",
        "subregion": "Caribbean",
        "emoji": "🇲🇫",
        "emojiU": "U+1F1F2 U+1F1EB"
    },
```
Saint Martin (French: Saint-Martin; Dutch: Sint Maarten)
