### ISSUE TITLE
Wrong States with Australia

### ISSUE THREAD

**Issue by second-2None** [dr5hn/countries-states-cities-database#14]
The states table contains results for Australia, country ID 14, that are not present in Australia. Will send through an update shortly

**Comment by DhanshreeA** [comment]
@dr5hn

**Comment by dr5hn** [comment]
@DhanshreeA @second-2None You'll see this fixes very soon.

**Comment by nishant-sethi** [comment]
@second-2None is this still open?

**Comment by dr5hn** [comment]
@nishant-sethi //cc @second_2None Issue has been fixed. Please verify.

**Comment by second-2None** [comment]
Awesome, I’ll take a look tonight and confirm for you.

**Comment by neutrino-dgada** [comment]
@second-2None  Did you get chance to look into it ?

**Comment by dr5hn** [comment]
@second-2None Did you get a chance to look into it ?

**Comment by second-2None** [comment]
Yeah they are all correct, 6 states and 2 territories.
