### ISSUE TITLE
City Reghin in Romania is missing

### ISSUE THREAD

**Issue by cornelpopa** [dr5hn/countries-states-cities-database#146]
https://en.wikipedia.org/wiki/Reghin
https://www.google.com/maps/place/Reghin/@46.7724464,24.6694561,13z/data=!3m1!4b1!4m5!3m4!1s0x474a37955620fe11:0x6a5589f7fca5fd3c!8m2!3d46.7710931!4d24.700762

**Comment by dr5hn** [comment]
@cornelpopa Thanks for reporting. 🎉 Will check it out soon.
