### ISSUE TITLE
Cities list STILL incorrect

### ISSUE THREAD

**Issue by paulpierre** [dr5hn/countries-states-cities-database#15]
Cities are still wrong, there are Italian cities duplicated in multiple countries in the JSON file, about 843 of them. Please look at how often "Acquaviva delle Fonti" repeats for example in the states of Korea "Kyeongsangbuk" it is repeated
![60200380-027c9e00-9814-11e9-9744-ed77162b517e](https://user-images.githubusercontent.com/142327/62069295-ebabdb80-b205-11e9-931e-7167c949419e.png)

**Comment by dr5hn** [comment]
@paulpierre Ok got it. Will fix this sooner.

**Comment by dr5hn** [comment]
@paulpierre Can you check now ?? I've fixed them all..

**Comment by paulpierre** [comment]
Looks great!
