### ISSUE TITLE
Model needs modification

### ISSUE THREAD

**Issue by Trozmagon** [dr5hn/countries-states-cities-database#154]
Hi dude, nice work on this, I just discovered it.

I've noticed there are some instances of countries that don't contain cities such as Hong Kong, Vatican City or Samoa, which is fine, it would mean data duplication but in the instances the model loses latitude/longitude for these locations.

Are you generating these locations automatically or are all updates community driven? I think it would be beneficial to include latitude/longitude for both Country and State, the case for state as well is for instance Western Australia (a State of Australia) which is such a large land mass it could include more information that most countries. It could be beneficial for anyone wanting to use this with maps.

I'm happy to help with any modifications if it's community driven but mostly asking in case you're able to script this before I start by hand :).

**Comment by dr5hn** [comment]
@Trozmagon Thanks for the suggestions 🎉 

- Modifications are open to all.
- For location updates or error fixes, I do manual research using Wikipedia & Wikidata and then fix them.
- If you can get me the modifications in JSON format I have a script available to push it in DB and then regenerate all other formats.
- For countries you can easily get Lat Long from here ==> https://restcountries.eu/rest/v2/all?fields=name;alpha3Code;latlng
- For states, it's gonna take a lot of effort.

**Comment by Trozmagon** [comment]
Nice one mate, I've written a script to read you're countries+states+cities.json file already so I'll make some modifications to that and see if we can get Country lat/lng incorporated and then I'll have a look at state later :). I'll get back to you soon.

**Comment by dr5hn** [comment]
@Trozmagon Just a note,

If you're making updates to JSON, then please use standalone JSON files.
For countries updates, use `countries.json` 
For states updates, use `states.json`

**Comment by Trozmagon** [comment]
will do

**Comment by Trozmagon** [comment]
Added countries, where do you get your State information from?

**Comment by Trozmagon** [comment]
Nevermind, I've been able to script all the info out of Google Maps API, should have some data to commit shortly.

**Comment by dr5hn** [comment]
@Trozmagon Ok fine, let me know if you need anything else.

**Comment by Trozmagon** [comment]
All good, I've submitted the changes so I'll close this off, thanks mate :)

**Comment by dr5hn** [comment]
@Trozmagon 

Mate, you forgot to Raise a Pull Request.

**Comment by Trozmagon** [comment]
Ahhh sorry mate, I didn't actually pull the source, I just proposed the changes.

**Comment by dr5hn** [comment]
@Trozmagon Never mind, Thanks a ton.

**Comment by Trozmagon** [comment]
I've written a small .net core app to get Countries, States and Cities from your json files and then Search google maps API for each of them if you would like me to send it to you?

I didn't propose it here because it's in .net not php and my Models are quite different to yours but it wouldn't be hard to modify.

**Comment by dr5hn** [comment]
@Trozmagon Wow!! that's awesome 😎

I would love to see it !! Can you please share ?

**Comment by Trozmagon** [comment]
I've ripped it out of my main solution and dumped it here: @Trozmagon/LocationScraper

But it won't run without a database connection a google maps API key but you'll get the idea from the code.

**Comment by dr5hn** [comment]
@Trozmagon Nice, Thanks for sharing.
