### ISSUE TITLE
Duplicate state names for Germany

### ISSUE THREAD

**Issue by binoyudayan** [dr5hn/countries-states-cities-database#16]
1. There two states named **Rheinland-Pfalz** and [**Rhineland-Palatinate**](https://en.wikipedia.org/wiki/Rhineland-Palatinate), actually both are same state. One is German name and other one is English name. And the cities belongs to both are different, but it can be included in any one of them(I have done a random check in google maps).
2. Also [Niederwerth](https://www.google.com/maps/place/56179+Niederwerth/@50.3960567,7.5782025,14z/data=!3m1!4b1!4m5!3m4!1s0x47be7d2c6c167ee1:0x422d4d510daed90!8m2!3d50.3954673!4d7.6088034) can be added to Rheinland-Pfalz
3. The same issue there with Baveria and Bayern
The issue there in country+states+cities, countries+states json and cties, world sql files. Raising this issue to know if it's intentional or a bug.

Thank you.

**Comment by dr5hn** [comment]
@binoyudayan Thanks for debugging. Will fix it asap.

**Comment by dr5hn** [comment]
@binoyudayan Can you check now ?? I've fixed them all..

**Comment by dr5hn** [comment]
@binoyudayan Closing this issue as its fixed now.

**Comment by binoyudayan** [comment]
ya.. thank you!
