### ISSUE TITLE
Table cities column name is updated_on instead updated_at

### ISSUE THREAD

**Issue by cornelpopa** [dr5hn/countries-states-cities-database#165]
Table cities column name is updated_on instead updated_at

I think that updated_at would make more sense as it respects the naming convention from other tables (world, countries, etc) and also adheres to the same naming convention from different frameworks (f.e. laravel).

**Comment by dr5hn** [comment]
@cornelpopa I agree with you. 

Thanks for the suggestion, will get it updated soon.

**Comment by dr5hn** [comment]
@dr5hn Reminder to Myself.

* Need to add Schumen city

**Comment by dr5hn** [comment]
@cornelpopa Finally added Shumen as a City.
