### ISSUE TITLE
Can't get Cities if there's no State!

### ISSUE THREAD

**Issue by UtopiaBe** [dr5hn/countries-states-cities-database#166]
Some countries like [Asland Islands] don't have a state. So it is not possible to get Cities of Asland Islands because there are no state code:
https://api.countrystatecity.in/v1/countries/AX/states/**XX**/cities

Any idea on making possible to get all Cities by Country?

**Comment by dr5hn** [comment]
@UtopiaBe It's very much possible. Let me push an update to API with this ability. I will keep you posted.

Thank you so much for raising this issue.

**Comment by dr5hn** [comment]
@UtopiaBe One more thing, For this particular country "Ashland Islands". If you don't see any states, there won't be any cities' existence in DB. Since cities are dependent on `state_id`.

**Comment by dr5hn** [comment]
@UtopiaBe I have made the API available to you.
https://api.countrystatecity.in/v1/countries/AX/cities

**Comment by UtopiaBe** [comment]
Wow! That was quick 🥇 
I will try to make an Russian translations, so if you want i will contribute it.

**Comment by dr5hn** [comment]
@UtopiaBe Thanks.

Sure, I will be waiting.

**Comment by qxygene** [comment]
> 

When you are planning to contribute?
