### ISSUE TITLE
Currency Symbols

### ISSUE THREAD

**Issue by oyeaussie** [dr5hn/countries-states-cities-database#169]
Hello,

Please see attached json file.

Maybe you can include the currency symbols in your next release.

Symbols are good to have for e-commerce websites to show it on invoices or cart.

Thanks.
[src.zip](https://github.com/dr5hn/countries-states-cities-database/files/5854160/src.zip)

**Comment by dr5hn** [comment]
@oyeaussie That's awesome !! 

Thank you so much for your contribution.

Really Appreciated. 🎉
