### ISSUE TITLE
currency symbol is null

### ISSUE THREAD

**Issue by oyeaussie** [dr5hn/countries-states-cities-database#173]
https://github.com/dr5hn/countries-states-cities-database/blob/ebaacfbe061f19cec10d6572f4587d2a3beb78ad/scripts/export.php#L61

currency_symbol is null in countries+state+cities.json file.

**Comment by dr5hn** [comment]
@oyeaussie My Bad :( Let me fix it real quick. Thanks for the heads up !

**Comment by dr5hn** [comment]
@oyeaussie Fixed. Can you please verify now?
