### ISSUE TITLE
Wrong column mapping in countries.csv file

### ISSUE THREAD

**Issue by miststudent2011** [dr5hn/countries-states-cities-database#177]
|id |name         |iso3|iso2|phone_code|capital  |currency|currency_symbol|native   |region|subregion      |translations                                                                                                               |latitude   |longitude  |emoji|emojiU         |
|---|-------------|----|----|----------|---------|--------|---------------|---------|------|---------------|---------------------------------------------------------------------------------------------------------------------------|-----------|-----------|-----|---------------|
|1  |Afghanistan  |AFG |AF  |93        |Kabul    |AFN     |؋              |افغانستان|Asia  |Southern Asia  |[{zoneName:'Asia\/Kabul',gmtOffset:16200,gmtOffsetName:'UTC+04:30',abbreviation:'AFT',tzName:'Afghanistan Time'}]          |33.00000000|65.00000000|🇦🇫 |U+1F1E6 U+1F1EB|
|2  |Aland Islands|ALA |AX  |+358-18   |Mariehamn|EUR     |€              |Åland    |Europe|Northern Europe|[{zoneName:'Europe\/Mariehamn',gmtOffset:7200,gmtOffsetName:'UTC+02:00',abbreviation:'EET',tzName:'Eastern European Time'}]|60.11666700|19.90000000|🇦🇽 |U+1F1E6 U+1F1FD|

Wrong column mapping in [countries.csv](https://github.com/dr5hn/countries-states-cities-database/blob/master/csv/countries.csv) file , timezone values are mapped to translations and translations data is not present in the csv file where as it is present in [json file](https://github.com/dr5hn/countries-states-cities-database/blob/master/countries.json).

**Comment by dr5hn** [comment]
@miststudent2011 Thanks for reporting. 👍🏼 

Will fix it soon. 🎉
