### ISSUE TITLE
Too many records are repeating in Cities

### ISSUE THREAD

**Issue by neelabh2010** [dr5hn/countries-states-cities-database#178]
I found, there are some city records that are repeated.
It is under INDIA -> Uttar Pradesh ->
**1) Agra and Āgra**
**Agra**
{
  "id": 57601,
  "name": "Agra",
  "state_id": 4022,
  "state_code": "UP",
  "country_id": 101,
  "country_code": "IN",
  "latitude": "27.18333000",
  "longitude": "78.01667000"
}
**Āgra**
{
  "id": 134453,
  "name": "Āgra",
  "state_id": 4022,
  "state_code": "UP",
  "country_id": 101,
  "country_code": "IN",
  "latitude": "27.08333000",
  "longitude": "77.96667000"
}

**2) Amethi and Amethī**
**Amethi**
{
  "id": 57677,
  "name": "Amethi",
  "state_id": 4022,
  "state_code": "UP",
  "country_id": 101,
  "country_code": "IN",
  "latitude": "28.01667000",
  "longitude": "81.05000000"
}

**Amethī**
{
  "id": 57678,
  "name": "Amethī",
  "state_id": 4022,
  "state_code": "UP",
  "country_id": 101,
  "country_code": "IN",
  "latitude": "26.15696000",
  "longitude": "81.80519000"
}

**2) Āzamgarh and Azamgarh**
 **Āzamgarh**
 {
  "id": 134470,
  "name": "Āzamgarh",
  "state_id": 4022,
  "state_code": "UP",
  "country_id": 101,
  "country_code": "IN",
  "latitude": "26.00000000",
  "longitude": "83.00000000"
}

**Azamgarh**
{
  "id": 57777,
  "name": "Azamgarh",
  "state_id": 4022,
  "state_code": "UP",
  "country_id": 101,
  "country_code": "IN",
  "latitude": "26.06832000",
  "longitude": "83.18358000"
}

**3) Basti and Bastī**
**Basti**
{
  "id": 57901,
  "name": "Basti",
  "state_id": 4022,
  "state_code": "UP",
  "country_id": 101,
  "country_code": "IN",
  "latitude": "26.82816000",
  "longitude": "82.77924000"
}
**Bastī**
{
  "id": 57902,
  "name": "Bastī",
  "state_id": 4022,
  "state_code": "UP",
  "country_id": 101,
  "country_code": "IN",
  "latitude": "26.78817000",
  "longitude": "82.71617000"
}

likewise ...
**3) Faizābād and Fyzābād**
**4) Fīrozābād and Firozabad**
**5) Ghazīpur and Ghāzīpur**
**6) Gonda and Gondā City**
**7) Hardoi and Hardoī**
**8) Hardoi and Hardoī**
**9) Jalālābad and Jalālābād**
**10) Rāe Bareli and Raebareli**

So many more could be there and I think one of the duplicated records should be removed from the database.

**Comment by dr5hn** [comment]
@neelabh2010 Thanks for reporting. 👍🏼 

Will look into it.
