### ISSUE TITLE
Project LICENSE

### ISSUE THREAD

**Issue by JoelFernando209** [dr5hn/countries-states-cities-database#179]
Hello, do the license of the project is MIT? Can you please specify the project license in Github? I actually cannot find it, i'm making an NPM package with the help of the API of this project and i don't know if i can use it... Thanks!

**Comment by dr5hn** [comment]
@JoelFernando209 This is a Free Database, available all across the internet. You can use it for free. 

There are already few NPM packages built using this DB.

**Comment by JoelFernando209** [comment]
Thanks for the answer!

> @JoelFernando209 This is a Free Database, available all across the internet. You can use it for free.
> 
> There are already few NPM packages built using this DB.

**Comment by hirako2000** [comment]
I think an explicit license would help a lot avoid ambiguity on what 'free' means.

**Comment by dr5hn** [comment]
@hirako2000 //cc @JoelFernando209 

Done. Added License. 👍🏼
