### ISSUE TITLE
Add Country domain tld field in the list 

### ISSUE THREAD

**Issue by miststudent2011** [dr5hn/countries-states-cities-database#180]
It would be nice if we have country domain tld  included in the list. 

We can have refernce data from the below URL.

[country-by-domain-tld.json](https://github.com/samayo/country-json/blob/master/src/country-by-domain-tld.json)

It would also be good if we add other fields that are present in the referenced [repo](https://github.com/samayo/country-json).

**Comment by dr5hn** [comment]
@miststudent2011 Thanks for the suggestion.

Will try to implement them soon.
