### ISSUE TITLE
A lot of errors

### ISSUE THREAD

**Issue by Vikrant659** [dr5hn/countries-states-cities-database#181]
I was using this database. And there are a lot of errors. I.e. 
The continents provided in countries table are outdated( e.g. Americas continent is not used anymore).
The State iso2 column have a lot of numeric values that are not valid.
There are many duplicate values in cities table as well.(For e.g. when selected Asia->India->Uttarakhand then Dehradun is coming twice)
Otherwise its the best I have found on the internet for free. But really appreciate if the bugs are fixed.

**Comment by dr5hn** [comment]
@Vikrant659 Thanks for reporting. 🎉 

Regarding, 
- Continents: If you have any good sources where i can get a accurate list of continents, please let me know.
- State [ISO2] Values - I grab a data from wikidata.org, If you've got any good source where i can get accurate list of ISO2 for all states, please let me know.
- Duplicates: Fixable, i've already got a Bug request from other user as well. Its currently WIP. - Same as #178

**Comment by dr5hn** [comment]
UPDATE: Fixed India's Duplicate Cities.

**Comment by Vikrant659** [comment]
@dr5hn 
Thanks for getting back in such short span of time and fixing some of the issues.
I don't know which tool do you use to scrap the data from those source but I do have some sources where you can find some accurate data:-

1) https://www.back4app.com/database/back4app/list-of-all-continents-countries-cities
 - You have to create app here and get data accordingly.
 
 2) https://ipinfodb.com/free-database
 - You can check here as well.
 
 3) https://www.geonames.org/ 
 - This has a lot of accurate data available as well
 
 Please let me know if it were useful

**Comment by dr5hn** [comment]
@Vikrant659 Thanks for the sources info. 

I will take a look at it soon. Probably gonna take a longer time to implement. I am doing my best to keep data accuracy at maximum level.

**Comment by dr5hn** [comment]
@Vikrant659 I have confirmed from many sources and seems like numeric values in ISO2 are valid. 
Even one of your suggested sources has the ISO2 as numerical values.

![Screenshot 2021-04-11 at 9 09 46 PM](https://user-images.githubusercontent.com/6929121/114310956-5dc37180-9b0a-11eb-9be5-b4d56bc10379.png)

**Comment by dr5hn** [comment]
@Vikrant659 Regarding the continent we have divided our data into 2 columns region and subregion and this data are taken from the very latest and updated source [here](https://restcountries.eu/rest/v2/all?fields=name;alpha3Code;region;subregion).

**Comment by Vikrant659** [comment]
@dr5hn Thanks alot for looking into the matter and resolving it. Looking forward to use it in my project.
Again thankyou.
