### ISSUE TITLE
Spain: missing cities

### ISSUE THREAD

**Issue by Melchyore** [dr5hn/countries-states-cities-database#184]
Hello!

First of all, thanks for this wonderful database!

I was testing the demo and I noticed that many Spain's states are missing cities (e.g. Madrid Province & Barcelona Province).

Keep up the good work!

**Comment by dr5hn** [comment]
@Melchyore Thanks for reporting. 🎉 

If you've got more examples, please post it here.

I will take a look at it soon.

**Comment by Melchyore** [comment]
@dr5hn I'm not sure but I think that many cities are children of states "Andalusia", "Aragon", "Castile-La Mancha".

In fact, there are duplicates (e.g. Community of Madrid and Madrid Province, the first one has cities but not the second). I think some cities has endTime (not exist anymore) but are listed.

Some examples:
- Murcia province, Region of Murcia
- Community of Madrid, Madrid Province
- Barcelona Province (Barcelona is children of Catalonia in the dabatase)

Spain has only 17 communities (states):
- Andalusia
- Aragon
- Asturias
- Balearic Islands
- Basque Country
- Canary Islands
- Cantabria
- Castilla–La Mancha
- Castile and León
- Catalonia
- Extremadura
- Galicia
- La Rioja
- Community of Madrid
- Murcia
- Navarre
- Valencian Community

... but there're more than 17 in database.

Hope it helps!

**Comment by dr5hn** [comment]
@Melchyore This is very helpful.

Thanks. I will take a look at it soon.
