### ISSUE TITLE
Add City

### ISSUE THREAD

**Issue by faridmdnor** [dr5hn/countries-states-cities-database#186]
Please add new states to country Malaysia

WP Putrajaya
WP Labuan

**Comment by dr5hn** [comment]
@faridmdnor Thanks for reporting 🎉.

Will add it soon.

**Comment by dr5hn** [comment]
@faridmdnor These states and cities do already exist in DB.
![Screenshot 2021-04-11 at 8 19 46 PM](https://user-images.githubusercontent.com/6929121/114309124-c824e380-9b03-11eb-8cf3-a952e0499cca.png)
