### ISSUE TITLE
[BUG] City listed in states of Poland

### ISSUE THREAD

**Issue by DanielKucal** [dr5hn/countries-states-cities-database#187]
Poland has 16 "states" (voivodeships, województw) while `csc.getStateOfCountry('PL')` returns 17, because there is one unwanted entry:
```json
  {
    "name": "Kielce",
    "isoCode": "KI",
    "countryCode": "PL",
    "latitude": "50.86607730",
    "longitude": "20.62856760"
  },
```
Kielce is a Polish capital city of Świętokrzyskie Voivodeship, not separate state.

https://en.wikipedia.org/wiki/Administrative_divisions_of_Poland

**Comment by dr5hn** [comment]
@DanielKucal  Thanks for reporting. 🎉 

Will fix it ASAP.
