### ISSUE TITLE
Algeria has 10 new provinces (states/wilayas)

### ISSUE THREAD

**Issue by Melchyore** [dr5hn/countries-states-cities-database#188]
Algeria has added recently 10 new provinces (wilayas) and has now 58 provinces: [Provinces of Algeria](https://en.wikipedia.org/wiki/Provinces_of_Algeria) (from 49 to 58)

- El M'ghair
- El Menia
- Ouled Djellal
- Bordj Baji Mokhtar
- Béni Abbès
- Timimoun
- Touggourt
- Djanet
- In Salah
- In Guezzam

Those new provinces were attached previously to other provinces.

**Comment by dr5hn** [comment]
@Melchyore Awesome !! Thanks for the update !!

Will add them soon !!

**Comment by Melchyore** [comment]
Thanks!
