### ISSUE TITLE
Italian cities are duplicated or incorrect

### ISSUE THREAD

**Issue by manuelricci** [dr5hn/countries-states-cities-database#19]
Hi, there are several errors with italian regions and cities. For example: Milan is not a region, but a city and Lombardia and Lombardy are the same things.

**Comment by dr5hn** [comment]
@manuelricci I know there are lot of issues with cities.. I am working on it to fix it up.. Will push final updates by next week.

**Comment by dr5hn** [comment]
@manuelricci Can you check now ?? I've fixed them all..

**Comment by dr5hn** [comment]
@manuelricci Closing this issue.as its already fixed now.
