### ISSUE TITLE
County Mures and Maramures are mixed (and one is missing) in Romania

### ISSUE THREAD

**Issue by cornelpopa** [dr5hn/countries-states-cities-database#198]
Hi, 

Some time ago I wrote you about the city Reghin Missing in Romania.  You were kind to add it for the moment "my" problem was solved.

But now I have realized that there is in fact a bigger problem in Romanian cities/states.

We have two (2) states (counties) with similar names:
1. Mureș County (https://en.wikipedia.org/wiki/Mure%C8%99_County)
2. Maramureș County (https://en.wikipedia.org/wiki/Maramure%C8%99_County) 

In your database the following occurs:
- Mures County (id 4760 in states) has all the data of Maramures County (only the name is wrong: Mures County instead of Maramures County). Correct repair would be to rename it Maramures County ( UPDATE `states` SET `name`='Maramureș County' WHERE  `id`=4760);
- 
- Database is missing completely the Mures County. All the cities from Mures County are missing from database (except Reghin which was added by you to the above wrongly named Mures County). This county should be created in database and added the proper cities to cities table. (https://en.wikipedia.org/wiki/Mure%C8%99_County#Administrative_divisions )

I would be happy to help you out with this but unfortunately I have no clue how to edit sql files with version control.
Only idea I had was to get the files into my mariadb server but on export the version control is lost - github marks entire file as different.

Please let me know if I can assist in any way to solve this issue.

**Comment by dr5hn** [comment]
@cornelpopa Thanks for reporting 🎉 

Yeah, it's very tedious to update SQL files. 

Well, I use MySQL and PHPMyAdmin to update those files. Since it's generated from PHPMyAdmin, it only shows different lines when pushing updated SQL files.

Anyways, I've fixed it, Please verify.

Thanks once again.
