### ISSUE TITLE
Missing Cities in Spain

### ISSUE THREAD

**Issue by jjwalker80j** [dr5hn/countries-states-cities-database#20]
Missing cities like Sitges in Spain (which is one of the most popular cities)

**Comment by dr5hn** [comment]
Yeah.. I know there are many issues with cities.. I working on it.. will fix them up by next week.

**Comment by dr5hn** [comment]
@jjwalker80j Can you check now ?? I've fixed them all..

**Comment by dr5hn** [comment]
@jjwalker80j closing this issue. As its already fixed now.
