### ISSUE TITLE
American Samoa doesn't have it's corresponding states and cities

### ISSUE THREAD

**Issue by nilachandan** [dr5hn/countries-states-cities-database#201]
I'm here, giving you just one example as in the case of "American Samoa". But many countries in your list, doesn't have its corresponding states. The list of countries with no states are as follows,

1. Aland Islands
2. American Samoa
3. Anguilla
4. Antarctica
5. Aruba
6. Bonaire, Sint Eustatius and Saba
7. Bouvet Island
8. British Indian Ocean Territory
9. Cayman Islands
10. Christmas Island
11. Cocos (Keeling) Islands
12. Cook Islands
13. Curaçao
14. Falkland Islands
15. Faroe Islands
16. French Guiana
17. French Polynesia
18. French Southern Territories
19. Gibraltar
20. Greenland
21. Greenland
22. Guadeloupe
23. Guam
24. Guernsey and Alderney
25. Heard Island and McDonald Islands
26. Jersey
27. Macau S.A.R.
28. Man (Isle of)
29. Martinique
30. Mayotte
31. Monaco
32. Montserrat
33. New Caledonia
34. Niue
35. Norfolk Island
36. Northern Mariana Islands
37. Palestinian Territory Occupied
38. Pitcairn Island
39. Puerto Rico
40. Reunion
41. Saint Helena
42. Saint Pierre and Miquelon
43. Saint-Barthelemy
44. Saint-Martin (French part)
45. Sint Maarten (Dutch part)
46. South Georgia
47. Svalbard And Jan Mayen Islands
48. Tokelau
49. Turks And Caicos Islands
50. United States Minor Outlying Islands
51. Vatican City State (Holy See)
52. Virgin Islands (British)
53. Virgin Islands (US)
54. Wallis And Futuna Islands
55. Western Sahara

**Comment by dr5hn** [comment]
@nilachandan Thanks for reporting. 🎉 

I will mark it as an improvement and will take a look at it soon.

**Comment by nilachandan** [comment]
Thank you.

**Comment by kunalfleethawks** [comment]
any updates on this?

**Comment by dr5hn** [comment]
@kunalfleethawks 

TBH, This is gonna take a longer time than expected.

**Comment by dr5hn** [comment]
@nilachandan //cc @kunalfleethawks 

On Updates,
Tried to find the data from the sources but couldn't find data for any of the countries below. Except one Monaco.. For that I will add states in DB soon.

1. Aland Islands	AX
2. American Samoa	AS
3. Anguilla	AI
4. Antarctica	AQ
5. Aruba	AW
6. Bouvet Island	BV
7. British Indian Ocean Territory	IO
8. Cayman Islands	KY
9. Christmas Island	CX
10. Cocos (Keeling) Islands	CC
11. Cook Islands	CK
12. Falkland Islands	FK
13. Faroe Islands	FO
14. French Guiana	GF
15. French Polynesia	PF
16. French Southern Territories	TF
17. Gibraltar	GI
18. Greenland	GL
19. Guadeloupe	GP
20. Guam	GU
21. Guernsey and Alderney	GG
22. Heard Island and McDonald Islands	HM
23. Jersey	JE
24. Macau S.A.R.	MO
25. Man (Isle of)	IM
26. Martinique	MQ
27. Mayotte	YT
28. Monaco	MC -- 3
29. Montserrat	MS
30. Bonaire, Sint Eustatius and Saba	BQ
31. New Caledonia	NC
32. Niue	NU
33. Norfolk Island	NF
34. Northern Mariana Islands	MP
35. Palestinian Territory Occupied	PS
36. Pitcairn Island	PN
37. Puerto Rico	PR
38. Reunion	RE
39. Saint Helena	SH
40. Saint Pierre and Miquelon	PM
41. Saint-Barthelemy	BL
42. Saint-Martin (French part)	MF
43. South Georgia	GS
44. Svalbard And Jan Mayen Islands	SJ
45. Tokelau	TK
46. Turks And Caicos Islands	TC
47. United States Minor Outlying Islands	UM
48. Vatican City State (Holy See)	VA
49. Virgin Islands (British)	VG
50. Virgin Islands (US)	VI
51. Wallis And Futuna Islands	WF
52. Western Sahara	EH
53. Curaçao	CW
54. Sint Maarten (Dutch part)	SX
