### ISSUE TITLE
ISO code for Iran (islamic republic of) states/provinces changed at 2020-11-24

### ISSUE THREAD

**Issue by mortezafs** [dr5hn/countries-states-cities-database#205]
Hello.

I looked at the Iran's data and saw that the province's ISO codes were wrong and needed to be corrected.
The ISO keys of provinces in this country have changed on 2020-11-24.

Change of subdivision code from IR-01 to IR-03, IR-02 to IR-04, IR-03 to IR-24, IR-04 to IR-10, IR-05 to IR-16, IR-06 to IR-18, IR-07 to IR-23, IR-08 to IR-14, IR-10 to IR-06, IR-11 to IR-19, IR-12 to IR-20, IR-13 to IR-11, IR-14 to IR-07, IR-15 to IR-08, IR-16 to IR-12, IR-17 to IR-05, IR-18 to IR-17, IR-19 to IR-01, IR-20 to IR-15, IR-21 to IR-02, IR-22 to IR-00, IR-23 to IR-22, IR-24 to IR-13, IR-25 to IR-21, IR-26 to IR-25, IR-28 to IR-26, IR-30 to IR-09, IR-31 to IR-28, IR-32 to IR-30 ;

Reference: 
https://www.iso.org/obp/ui/#iso:code:3166:IR

**Comment by dr5hn** [comment]
@mortezafs Thanks for reporting. 🎉

Awesome, I will fix it soon.

**Comment by mortezafs** [comment]
Thanks.

I looked more closely and realized that Hamedan province and a number of cities do not exist in your data set and i can help you to complete Iran's cities data.
I am temporarily involved in a project, but I will soon correct the information of Iran and send it to you to replace with current data.

Regards.
