### ISSUE TITLE
final  node_modules package size

### ISSUE THREAD

**Issue by kunalfleethawks** [dr5hn/countries-states-cities-database#206]
What is the final package size which will go in production build of any app? I see you have mentioned 387 MB. Is this source code size of package size? 

Thank you very much for awesome library.

**Comment by dr5hn** [comment]
@kunalfleethawks This is just a database repo.

However, there are two JS library which uses this database is
* [harpreetkhalsagtbit/country-state-city](https://github.com/harpreetkhalsagtbit/country-state-city)
* [ovictormacedo/country-state-city.js](https://github.com/ovictormacedo/country-state-city.js)

Assuming you're using one of them. They're currently using the JSON format of this database. So you need to check with them regarding package size.

**Comment by kunalfleethawks** [comment]
Thanks for clarification
