### ISSUE TITLE
The State/Region/County listings for Norway is not correct (administrative reorganization in 2020)

### ISSUE THREAD

**Issue by devNoustack** [dr5hn/countries-states-cities-database#207]
First of all, thank you for the time and effort you put into this project! :-)

FYI:

The Norwegian State/Region/County listings is not correct. The Norwegian parliament's reform reduced the number of counties from 19 to 11, which was implemented on 1 January 2020. The new counties is:

Troms og Finnmark
Nordland
Trøndelag
Møre og Romsdal
Vestland
Rogaland
Agder
Vestfold og Telemark
Viken
Oslo og Innlandet

Reference: https://en.wikipedia.org/wiki/Counties_of_Norway

**Comment by dr5hn** [comment]
@devNoustack Thanks for reporting. 🎉 

Really appreciated. Will take a look into it soon.

**Comment by devNoustack** [comment]
Hi again @dr5hn 

Do you have an ETA when it can be resolved?

**Comment by dr5hn** [comment]
@devNoustack No ETA..

As i see if i merge counties i need to accordingly move cities to proper counties.. and it's gonna take a good amount of time..

If you can help sorting this out by updating states.sql and cities.sql that would be great and raising a pull request.

Thanks

**Comment by devNoustack** [comment]
Here is a updated list: https://docs.google.com/spreadsheets/d/1gagPfOTyt0IpMQUGP6LwsaIfnfzJ9MyRb26g4CMrBis/edit?usp=sharing

**Comment by dr5hn** [comment]
@devNoustack There is a total of 668 cities/town currently in DB and according to your sheet, it's just 107 what about other cities/towns?

**Comment by dr5hn** [comment]
Closing this until the next reply.

**Comment by braaar** [comment]
Hello there! I am interested in resolving this issue and would be happy to contribute.

Here is an overview over the exact changes that were made 2018-2020:

| Old counties | New, merged county | Capital |
| ------------- | ------------- | ----------- |
| `Hordaland`, `Sogn og Fjordane` | `Vestland` | `Bergen` |
| `Vest-Agder`, `Aust-Agder` | `Agder` | `Kristiansand` |
| `Sør-Trøndelag`, `Nord-Trøndelag` | `Trøndelag` | `Steinkjer` |
| `Akershus`, `Buskerud`, `Østfold` | `Viken` | `Oslo` |
| `Oppland`, `Hedmark` | `Innlandet` | `Hamar` |
| `Troms`, `Finnmark` | `Troms og Finnmark` | `Tromsø` |
| `Vestfold`, `Telemark` | `Vestfold og Telemark` | `Skien` | 

If I understand the structure of the csv data correctly, this should only be a matter of doing a bunch of Find and Replace operations, and then just reviewing the changes to check for unintentional side effects. I'm not aware of any counties in other countries that use these exact names, but then again, we're talking about the whole world here, so there's always a chance.

How are the locations for counties determined? The location of the capital? Taken from google maps' pin for the county?

**Comment by braaar** [comment]
I'll start a PR this week.

**Comment by dr5hn** [comment]
@braaar Thanks for showing interest in contributing to the project.

I usually grab the states related information from the official site here. https://www.iso.org/obp/ui/#iso:code:3166:NO

And for coordinates, I search for that location in Google maps, copy the lat and long from the URL and paste it into MySQL Workbench / TablePlus / sequel ace.

Hope that answers your query. 👍🏼

**Comment by braaar** [comment]
Thanks for the reply, that is very helpful

**Comment by braaar** [comment]
I probably won't be working on this, so feel free, anyone :)
