### ISSUE TITLE
Spain - Galician and others not is a State, is a Region

### ISSUE THREAD

**Issue by tjaoc** [dr5hn/countries-states-cities-database#209]
The states:

https://en.wikipedia.org/wiki/Provinces_of_Spain

**Comment by tjaoc** [comment]
Cities of States Galician

https://es.wikipedia.org/wiki/Anexo:Municipios_de_Galicia_por_poblaci%C3%B3n

**Comment by tjaoc** [comment]
https://github.com/oscarnovasf/ccaa-provincias-municipios

**Comment by dr5hn** [comment]
@tjaoc Thanks for Reporting. 🎉 Really appreciate it.

TBH, This update looks very huge. Gonna take a longer time.

**Comment by tjaoc** [comment]
@dr5hn The List of States Spain, the others remove.

Albacete
Alicante
Almería
Álava
Asturias
Ávila
Badajoz
Islas Baleares
Barcelona
Bizkaia
Burgos
Cáceres
Cádiz
Cantabria
Castellón
Ceuta
Ciudad Real
Córdoba
Coruña
Cuenca
Gipuzkoa
Girona
Granada
Guadalajara
Huelva
Huesca
Jaén
León
Lleida
Lugo
Madrid
Málaga
Melilla
Murcia
Navarra
Ourense
Palencia
Palmas Las
Pontevedra
La Rioja
Salamanca
Santa Cruz de Tenerife
Segovia
Sevilla
Soria
Tarragona
Teruel
Toledo
Valencia
Valladolid
Zamora
Zaragoza

**Comment by tjaoc** [comment]
If you what this repo https://github.com/oscarnovasf/ccaa-provincias-municipios have the Communities, Province and Cities with correct relationship.

**Comment by dr5hn** [comment]
@tjaoc Finally got a chance to fix this. 🥂
