### ISSUE TITLE
Skipped a Step

### ISSUE THREAD

**Issue by viper2kx** [dr5hn/countries-states-cities-database#21]
I uploaded this and began to play with it. Since I live in the United States, I see all 50 states and a few of the U.S. Territories, but I am also seeing cities such as Byram in Mississippi and Trimble in Missouri, and other cities before selecting the proper state.

**Comment by dr5hn** [comment]
@viper2kx I am going to fix all the cities related issues by next week... I am working on it..

**Comment by dr5hn** [comment]
@viper2kx Can you check now ?? I've fixed them all..

**Comment by viper2kx** [comment]
I did a quick Ctrl+F and as far as I can see, it looks fixed.

Oh, cool, you have Latitude and Longitude now (or I just didn't notice those columns 3 weeks ago)
