### ISSUE TITLE
"Hell's Kitchen" is not a city

### ISSUE THREAD

**Issue by lastcoderz-codecaster** [dr5hn/countries-states-cities-database#211]
**Hell's Kitchen** in US_NYC is a neighborhood area (Q840133). Its city would be "New York City".

Wonder if there's an underlying issue causing this?! 
Will report if I find similar cases. Thanks!

**Comment by lastcoderz-codecaster** [comment]
Some similar examples producing noise in New York City are:
"Gramercy Park"
"Financial District"
"New York County" and "Manhattan" which I do believe are one and the same just different categorizations.

All of which should be supposedly areas in New York City; Not at the same level as NYC.

**Comment by dr5hn** [comment]
@lastcoderz-codecaster Sorry for the delayed response.

Thanks for reporting. I will take a look at it soon.
