### ISSUE TITLE
State codes

### ISSUE THREAD

**Issue by RonaldTayie** [dr5hn/countries-states-cities-database#212]
### state_code
`{
        "id": 82065,
        "name": "Caloocan",
        "state_id": 1347,
        **"state_code": "00",**
        "country_id": 174,
        "country_code": "PH",
        "latitude": "14.64953000",
        "longitude": "120.96788000"
    }`
The state_codes are not consistent with the state code for Philippine states for all the cities of the Philippines.

**Comment by RonaldTayie** [comment]
In the `cities.json` search for and delete all objects with **`"state_code": "00","country_id": 174,`**, there are about 36 objects.
I encountered the issue while loading the data into a database.

**Comment by dr5hn** [comment]
@RonaldTayie Got it. Thanks for reporting.🎉

Does this issue resolved for you?

**Comment by RonaldTayie** [comment]
YES
