### ISSUE TITLE
Portugal Error Cities in Viana do Castelo

### ISSUE THREAD

**Issue by tjaoc** [dr5hn/countries-states-cities-database#217]
<img width="512" alt="Captura de pantalla 2021-06-01 a las 20 02 09" src="https://user-images.githubusercontent.com/6704635/120370123-784ce680-c314-11eb-9cc3-901108aaf594.png">

The X it's invalid, not exist.

And please remove the word "District" not fine for the world and to people of Portugal

**Comment by dr5hn** [comment]
@tjaoc Thanks for Reporting. 🎉 

Will fix it soon.

**Comment by dr5hn** [comment]
@tjaoc May I know why these cities aren't valid?

- Areosa
- Darque
- Meadela
- Mozelos
- Valenza
-  Vila Praia de Âncora

**Comment by dr5hn** [comment]
@tjaoc However, I have removed the "District" word from Portugal states as of now. Will fix others soon.

**Comment by tjaoc** [comment]
@dr5hn  Valenza not is Valenza but Valença

The others not is a cities to State of Viana do Castelo

**Comment by dr5hn** [comment]
@tjaoc Ok thanks for confirming. I will take a look at them again.

**Comment by tjaoc** [comment]
@dr5hn I confirmed the States and it's ok.  Good Work
