### ISSUE TITLE
Issue in cities and state of United Kingdom 

### ISSUE THREAD

**Issue by BNG007** [dr5hn/countries-states-cities-database#218]
There is No state of West Midlands in that. Also Birmingham is a city not state.
<img width="464" alt="Screenshot 2021-06-02 at 12 21 08 PM" src="https://user-images.githubusercontent.com/83267062/120436801-04a2ec00-c39d-11eb-85e5-8d7c396808df.png">

**Comment by dr5hn** [comment]
@BNG007 Thanks for reporting. 🎉 

I think the issue looks similar to #168, Will try to look at it soon.

If you get some time, can you please check #168 as well?

**Comment by BNG007** [comment]
Yea. I guess i'm facing the same issue.
