### ISSUE TITLE
Data Related Issues

### ISSUE THREAD

**Issue by Amit270702** [dr5hn/countries-states-cities-database#219]
I've been just trying to get data of cities from this package. When I checked that there is a **city missing** from the data.
City Name: Pilibhit
State Name: Uttar Pradesh
State Code: UP
Country: India

I tried to use getCitiesOfState, getAllCities & getCitiesOfCountry methods provided.

This city was there in earlier versions of this package. But I can not find it now. Please take a look.
Thanks in advance for your help and efforts to provide & maintain such significant packages.

**Comment by dr5hn** [comment]
@Amit270702 Sure I will take a look at it soon.
