### ISSUE TITLE
Missing State and Cities  for Iran

### ISSUE THREAD

**Issue by pawanlapits** [dr5hn/countries-states-cities-database#228]
Hi Team , 

There are some state and cities which are not available into your code base.  I will share a list of all those. can you please add into your database.

**Comment by dr5hn** [comment]
@pawanlapits Sure, please share a list. Thanks.

**Comment by pawanlapits** [comment]
https://github.com/teamadlino/locations/tree/master/database/seeds

this library have complete list of iran state/province  and cities.   Please add missing item.

we need it very badly. thanks

**Comment by dr5hn** [comment]
@pawanlapits Sure, will try my best to add them soon. Thanks.

**Comment by pawanlapits** [comment]
please check all province and corresponding cities.  some province have incorrect cities

**Comment by pawanlapits** [comment]
Hi @dr5hn  any update on this ?

**Comment by dr5hn** [comment]
@pawanlapits Well, no update so far... TBH, it's gonna take a good amount of time. No ETA...

If possible, I will try to take a look this weekend.

Thanks

**Comment by dr5hn** [comment]
@pawanlapits Fixed in #481
