### ISSUE TITLE
Duplicate cities

### ISSUE THREAD

**Issue by Dr-Phone** [dr5hn/countries-states-cities-database#230]
{
    "id": 1679,
    "name": "Arnoldstein",
    "latitude": "46.54611000",
    "longitude": "13.71000000"
},
{
    "id": 143784,
    "name": "Arnoldstein",
    "latitude": "46.55055556",
    "longitude": "13.70388889"
},

---

{
    "id": 143787,
    "name": "Bad Kleinkirchheim",
    "latitude": "46.81361111",
    "longitude": "13.79277778"
},
{
    "id": 143788,
    "name": "Bad Kleinkirchheim",
    "latitude": "46.84279000",
    "longitude": "13.79123000"
},

---

{
    "id": 1816,
    "name": "Brückl",
    "latitude": "46.75167000",
    "longitude": "14.53667000"
},
{
    "id": 143789,
    "name": "Brückl",
    "latitude": "46.75305556",
    "longitude": "14.53583333"
},

---

{
    "id": 1833,
    "name": "Dellach",
    "latitude": "46.66175000",
    "longitude": "13.07965000"
},
{
    "id": 143790,
    "name": "Dellach",
    "latitude": "46.66138889",
    "longitude": "13.07944444"
},

---

{
      "id": 1969,
      "name": "Feistritz im Rosental",
      "latitude": "46.51667000",
      "longitude": "14.16667000"
  },
  {
      "id": 143795,
      "name": "Feistritz im Rosental",
      "latitude": "46.52250000",
      "longitude": "14.17166667"
  },

---

{
    "id": 1981,
    "name": "Ferndorf",
    "latitude": "46.73651000",
    "longitude": "13.62661000"
},
{
    "id": 143796,
    "name": "Ferndorf",
    "latitude": "46.73611111",
    "longitude": "13.62638889"
},

---

{
    "id": 2015,
    "name": "Frauenstein",
    "latitude": "46.81417000",
    "longitude": "14.29417000"
},
{
    "id": 143798,
    "name": "Frauenstein",
    "latitude": "46.81361111",
    "longitude": "14.36750000"
},

---

{
    "id": 2024,
    "name": "Friesach",
    "latitude": "46.95528000",
    "longitude": "14.40583000"
},
{
    "id": 143799,
    "name": "Friesach",
    "latitude": "46.95250000",
    "longitude": "14.40972222"
},

---

{
  "id": 2113,
  "name": "Grafenstein",
  "latitude": "46.61393000",
  "longitude": "14.46719000"
},
{
  "id": 143804,
  "name": "Grafenstein",
  "latitude": "46.61500000",
  "longitude": "14.46722222"
},

---

{
    "id": 90029,
    "name": "Baia Mare",
    "latitude": "47.65729000",
    "longitude": "23.56808000"
},
{
    "id": 95111,
    "name": "Baia Mare",
    "latitude": "47.74048000",
    "longitude": "23.60337000"
},
{
    "id": 90030,
    "name": "Baia Sprie",
    "latitude": "47.66189000",
    "longitude": "23.69215000"
},
{
    "id": 95455,
    "name": "Baia Sprie",
    "latitude": "47.66446000",
    "longitude": "23.66970000"
},

**Comment by dr5hn** [comment]
@Dr-Phone Thanks for reporting. 🎉 

I will look at it soon.

**Comment by oguzhanbulut** [comment]
@dr5hn example data:

Turkey -> Yozgat -> Akdagmadeni
Turkey -> Yozgat -> Akdagmadeni İlcesi
