### ISSUE TITLE
A comprehensive list of possible duplicates

### ISSUE THREAD

**Issue by jacy33** [dr5hn/countries-states-cities-database#236]
Hello! :)

I've prepared a list of possible duplicated cities(4341 records) by iterating through every city looking for any corresponding record with a **distance of fewer than 500 meters**.

There's also a `Hi-Conf` column in the spreadsheet indicating matching the names of the two cities. For starters, it's okay to start out by pruning the Hi-Conf ones.

Each city is repeated only once in the sheet.

### Spreadsheet:
[https://drive.google.com/file/d/17BNlXUk9-AfkbOtNgoWJqptg0y0uAbo6/view?usp=sharing](https://drive.google.com/file/d/17BNlXUk9-AfkbOtNgoWJqptg0y0uAbo6/view?usp=sharing)

I can share the query used to reproduce the results if it's needed.

Thank you for all the work you put in!

**Comment by dr5hn** [comment]
@jacy33 Thanks for putting effort into the findings. 🎉  Really appreciated.

I will check it out soon and let you know if anything is required.

**Comment by dr5hn** [comment]
@jacy33 I reviewed the sheet and found that this isn't the ideal way to solve duplicates. Hence closing.

I successfully removed 400 records of duplicates by a different method of matching exact city name match and if those both cities lies in same state.
