### ISSUE TITLE
TS Support

### ISSUE THREAD

**Issue by kishanio** [dr5hn/countries-states-cities-database#237]
Is it possible to generate / add declaration files for typescript? 

Let me know if you require assistance for this.

**Comment by dr5hn** [comment]
@kishanio Are you referring to this NPM Package ? 👉🏻 https://github.com/harpreetkhalsagtbit/country-state-city

This is just a RAW DB repository.

**Comment by kishanio** [comment]
@dr5hn Oops. My bad. I'll open issue on same.
