### ISSUE TITLE
States latitude, longitude missing in countries+states+cities.json file.

### ISSUE THREAD

**Issue by iamhitya** [dr5hn/countries-states-cities-database#242]
All States latitude, longitude missing in countries+states+cities.json file.

![image](https://user-images.githubusercontent.com/18601967/123567373-9e648a00-d7df-11eb-87c8-265e68a1c6d8.png)

**Comment by dr5hn** [comment]
@iamhitya Thanks for reporting. 🎉 

Will fix it soon.
