### ISSUE TITLE
Request an API check

### ISSUE THREAD

**Issue by ArashZich** [dr5hn/countries-states-cities-database#247]
Dear Darshan Gada 
I am a programmer from Iran. Currently, I am developing an application. 
In my application, I used the API announced on your site. It seems that some parts do not work properly in the new update that you have created in the API. For example, locations in Iran and Turkey do not work properly. The states of Iran and Turkey are doing well, but the cities shown for each state are wrong.
It is worthwhile to check this case and if possible, let me know if I can use your API in my application or not.

Sincerely
ArashZich

**Comment by dr5hn** [comment]
@ArashZich 

Regarding Iran, I've got one issue submission here. ISO code previously entered was incorrect.
https://github.com/dr5hn/countries-states-cities-database/issues/205

If you see, there's been a major update in ISO code, and the source of the correction is from the official site of the ISO.

As per my assumption, you are passing old ISO code and hence it's returning to the wrong cities.

Let me know if my assumptions are correct or send me a sample API URL that you're referring to that has incorrect
data. Along with the full name of the state.

**Comment by ArashZich** [comment]
Dear Darshan Gada
Thank you for your response.
According to the link "https://www.iso.org/obp/ui/#iso:code:3166:IR" 
which is the main ISO code, for example: “IR-30 Alborz” is for Alborz State, 
but with the link https://api.countrystatecity.in/v1/countries/[ciso]/states/[siso]/cities
If we give it “IR-30 Alborz”, instead of the cities of Alborz state, it shows the cities belonging to “IR-09 Khorāsān-e Raẕavī”, which is as shown in the picture below.
![Screenshot from 2021-07-10 19-17-09](https://user-images.githubusercontent.com/33162969/125168353-72231300-e1ba-11eb-81de-1a4cb2317df5.png)
Or another example of “IR-07 Fars”, which belongs to Fars state, mistakenly shows the cities of “Tehran state”.
![Screenshot from 2021-07-10 19-19-07](https://user-images.githubusercontent.com/33162969/125168365-8109c580-e1ba-11eb-8c11-8a24ff7166a5.png)
I get the list of states from the link "https://api.countrystatecity.in/v1/states". 
Your site demo is correct, but I encounter these problems when I use the above links in my application.

**Comment by dr5hn** [comment]
@ArashZich Yes, you're right!

API DB is not up to date. Will update it soon.

**Comment by dr5hn** [comment]
@ArashZich The API DB has been updated to the latest. You may now have the correct mapping of states and cities.

**Comment by yasirmehmood123** [comment]
@dr5hn Hi,
i have request the Apikey for this but haven't got yet its has been more than a day now

**Comment by dr5hn** [comment]
@yasirmehmood123 Please read the FAQs section.
https://countrystatecity.in/faq/#-how-much-time-it-will-take-to-receive-api-key

**Comment by yasirmehmood123** [comment]
@dr5hn thanks
let me wait for a day more :)
