### ISSUE TITLE
Translate country name into Korean.

### ISSUE THREAD

**Issue by ragubyun** [dr5hn/countries-states-cities-database#248]
Hi, team.

I just translated country name into Korean and added it to countries.sql and world.sql.

**Comment by dr5hn** [comment]
@ragubyun Thank you, Really appreciate your efforts !!

Can you please raise a pull request?

**Comment by ragubyun** [comment]
#249 🙏

**Comment by dr5hn** [comment]
@ragubyun Once again thank you so much for your contribution.
