### ISSUE TITLE
complete

### ISSUE THREAD

**Issue by i7eo** [dr5hn/countries-states-cities-database#256]
This data is far more complete than Shopify's, and although it will cost me a lot more time to clean up the data, thank you anyway! 👍

**Comment by dr5hn** [comment]
@i7eo  you're welcome.

Btw what type of cleanup required?

If you get this data cleanup, would you mind sharing here?

**Comment by i7eo** [comment]
> @i7eo you're welcome.
> 
> Btw what type of cleanup required?
> 
> If you get this data cleanup, would you mind sharing here?

Just like Shopify address data.
I'll come back and submit the PR when I'm done.😉

**Comment by i7eo** [comment]
I find some errors in this `countries+states+cities.json` data.

Four countries not have phone_code., like: 

```javascript
"name": "Antarctica",
"phone_code": "672"
```

```javascript
"name": "French Southern and Antarctic Lands",
"phone_code": "33"
```

```javascript
"name": "Heard Island and McDonald Islands",
"phone_code": "672"
```

```javascript
"name": "South Georgia and South Sandwich Islands",
"phone_code": "500"
```

**Comment by dr5hn** [comment]
@i7eo I've taken phone_code from this source.

**Comment by i7eo** [comment]
> @i7eo I've taken phone_code from this source.
> https://restcountries.eu/rest/v2/all?fields=name;callingCodes

All right, I'll check again
