### ISSUE TITLE
cities.sql

### ISSUE THREAD

**Issue by abdullahsalma** [dr5hn/countries-states-cities-database#260]
`"31373", "Mansourah"`
and
`"31374", "Mansoûra"`

City in Algeria, `المنصورة` can be written both the previous cities. I believe these are duplicates. the correct form ends with `h`.

like my name. Abdullah. You can write Abdulla. still, be correct, but Abdullah is more accurate.

https://www.google.com/maps/place/Mansourah,+Algeria/@34.8723325,-1.3888449,13z/data=!3m1!4b1!4m5!3m4!1s0xd78c872578de5d1:0x57392e401cc5e7e8!8m2!3d34.8789634!4d-1.3486934 

EDIT:

found this other Mansura but the location is different. do not know if this is `31374`
https://www.google.com/maps/place/Mansoura,+Algeria/@32.0225619,2.7787166,9z/data=!3m1!4b1!4m13!1m7!3m6!1s0x1265d311f20351e5:0x615fd044ec1729e1!2sMetlili,+Algeria!3b1!8m2!3d32.291202!4d3.6031681!3m4!1s0x1266757e58b6ee39:0xff12cb0ef2826636!8m2!3d31.9719689!4d3.4112549

**Comment by dr5hn** [comment]
@abdullahsalma Both are different. Hence closing.
