### ISSUE TITLE
countries.sql

### ISSUE THREAD

**Issue by abdullahsalma** [dr5hn/countries-states-cities-database#271]
id 194 Saudi Arabia. 
correct native is المملكة العربية السعودية instead of العربية السعودية (never been used).
المملكة العربية السعودية means Kingdom of Saudi Arabia.

https://en.wikipedia.org/wiki/Saudi_Arabia
".. officially the Kingdom of Saudi Arabia.." 
on the right, you can see it as ٱلْمَمْلَكَة ٱلْعَرَبِيَّة ٱلسَّعُوْدِيَّة. But that is too formal for website use, we write it as المملكة العربية السعودية.

Thank you.
Abdullah Salma

**Comment by dr5hn** [comment]
@abdullahsalma Which one is the final one?

**Comment by abdullahsalma** [comment]
المملكة العربية السعودية
