### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by dineshkp** [dr5hn/countries-states-cities-database#272]
Hello, I would like to use the database for an API we are building in our organisation. The purpose is to be able to fetch countries, states and cities for use in drop-downs. There can also be scenarios where we may add missing cities to the database.

My doubt is:  the license (ODbL) requires disclosing source, does that mean only the modified database we would be building/using or the source code of the API as well.

Thank you!

**Comment by dr5hn** [comment]
@dineshkp 
I believe, It's about a modified database only.

**Comment by dr5hn** [comment]
@dineshkp Does it solved your doubt?

**Comment by dr5hn** [comment]
Closing this issue for now. Please feel free to open an issue.

**Comment by dineshkp** [comment]
@dr5hn Apologies for the delay. I am still not clear about it.

Is it sufficient if only the modified database is made available open-source? We are building pipelines to help maintain the database stay up to date with the source and also support custom changes/corrections if required. We may not be able to fork your repository as such, is that ok ? We can add a credit in the README file if required, does this work ?

**Comment by dr5hn** [comment]
@dineshkp Yes, that's completely fine. Don't worry too much about the license.

Credit in README will work as well.

**Comment by dineshkp** [comment]
@dr5hn Thank you!
