### ISSUE TITLE
Install Package

### ISSUE THREAD

**Issue by mariohmol** [dr5hn/countries-states-cities-database#281]
Would be great if u could provide this to be installed as a npm package!! 

thanks for the awesome repo!

**Comment by dr5hn** [comment]
@mariohmol Sure.. here you go

https://www.npmjs.com/package/country-state-city

**Comment by mariohmol** [comment]
awesome!!!! thank you.. if u could put it on readme will help people to find out!

thanks a lot!

**Comment by dmitryuk** [comment]
The library https://www.npmjs.com/package/country-state-city abandoned
