### ISSUE TITLE
world.sql can't be imported twice - will fail with Cannot add foreign key constraint

### ISSUE THREAD

**Issue by feliperaul** [dr5hn/countries-states-cities-database#286]
First of all, congrats on this amazing and useful project.

The world.sql file should be idempotent, which means it should be run again and again; when you update world.sql here, it would be a matter of downloading it and running it again.

However, if you run the world.sql file twice, you'll succeed the first time, but fail on all subsequent attempts:

```
# First attempt:
mysql -u user -ppass brand_new_mysql_table < world.sql
mysql: [Warning] Using a password on the command line interface can be insecure.
# Runs ok and data is loaded

mysql -u user -ppass brand_new_mysql_table < world.sql
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1215 (HY000) at line 147879: Cannot add foreign key constraint
```

That line contains `CREATE TABLE `countries` (`, and the end result is that `cities` and `states` were imported, but not countries (it disappears because the previous line, 147878, is a DROP TABLE IF EXISTS).

After the error, running `SHOW INNODB STATUS` on mysql console, it prints out this:

```
2021-08-07 14:19:03 0x70000cd05000 Error in foreign key constraint of table delete_me/states:
there is no index in referenced table which would contain
the columns as the first columns, or the data types in the
referenced table do not match the ones in table. Constraint:
,
  CONSTRAINT `country_region_final` FOREIGN KEY (`country_id`) REFERENCES `countries` (`id`)
The index in the foreign key in table is country_region
Please refer to http://dev.mysql.com/doc/refman/5.7/en/innodb-foreign-key-constraints.html for correct foreign key definition.
```

**Comment by dr5hn** [comment]
@feliperaul Thanks for reporting. 🎉 

I know about this annoying issue, I will spend some time and take a look at it.

**Comment by feliperaul** [comment]
@dr5hn As a quick-fix, we just added these 3 lines at the top of world.sql and it solves the problem.

```sql
DROP TABLE IF EXISTS `cities`;
DROP TABLE IF EXISTS `states`;
DROP TABLE IF EXISTS `countries`;
```

**Comment by dr5hn** [comment]
@feliperaul Thanks so much for the solution. However, I need to find a way to automate this fix.

**Comment by dr5hn** [comment]
@feliperaul Added a script to automate the process. https://github.com/dr5hn/countries-states-cities-database/commit/d416c1ccc818fe6d91b616f495fff4bcf6695b28

Won't be an issue anymore. Hence closing.

Once again thanks for the solution.
