### ISSUE TITLE
Wrong state name in Brazil - Federal District

### ISSUE THREAD

**Issue by feliperaul** [dr5hn/countries-states-cities-database#287]
State ID 2017, `Federal District`, should be named `Distrito Federal`.

**Comment by dr5hn** [comment]
@feliperaul Thanks for reporting. 🎉 

I will fix that up soon.

**Comment by dr5hn** [comment]
@feliperaul Fixed in https://github.com/dr5hn/countries-states-cities-database/commit/9aee2506c7705df6122e0342ac2f16cee7c3de66
