### ISSUE TITLE
DB vs JSON file and DB-Schema

### ISSUE THREAD

**Issue by emresaracoglu** [dr5hn/countries-states-cities-database#289]
Hello, 

Is it correct to import country, region, and city data into the database or use it over JSON?

It seems fine if I use it over the JSON file. Because I think this information is constantly updated. Therefore, it will be more comfortable to refresh the current information.  What is your idea about this?

Also, are only database schema files available?

Thank you.

**Comment by dr5hn** [comment]
@emresaracoglu Hi,

Both ways look good to me. 

There are always some goods using JSON format.
- If you're using only a few columns from SQL then prefer using JSON format.
- It will be easier to put a script on a cron job and get the data updated regularly. 

It was available previously, but I removed it. As it increased the manual work of updating them. You can easily grab them from `countries.sql`, `states.sql`, `cities.sql`.

Hope this helps.

**Comment by emresaracoglu** [comment]
Hello @dr5hn 

Thank you for your answer & your repo!
