### ISSUE TITLE
Saudia State Cities not mapped according to Source

### ISSUE THREAD

**Issue by ray-man** [dr5hn/countries-states-cities-database#291]
In mentioned source's demo Saudia's state `Eastern Province` has many cities but this library provides 0 cities in `Eastern Province`
<img width="1377" alt="Screenshot 2021-09-08 at 4 48 22 PM" src="https://user-images.githubusercontent.com/15623007/132504143-35de02d2-a6b6-4230-9518-7b72226b2d6a.png">

**Comment by dr5hn** [comment]
@ray-man Thanks for reporting. 🎉 

Will take a look at it soon.

**Comment by dr5hn** [comment]
@ray-man I can see many cities listed for `Eastern Province` in the screenshot. Are you referring this issue is in API?
