### ISSUE TITLE
Very long city name

### ISSUE THREAD

**Issue by nicmorais** [dr5hn/countries-states-cities-database#294]
There's a city called "Rd pt des Chataigniers, Rte de Milizac, Guilers, Finistère, France", which is the longest one in the CSV. Is this correct?

**Comment by dr5hn** [comment]
@nicmorais That looks fishy 🐟 . Thanks for Reporting.

Will take a look at it ASAP. 🎉

**Comment by nicmorais** [comment]
I think it's is a road in France, not a city. The actual "city" is named Guilers.

**Comment by dr5hn** [comment]
@nicmorais Ok Thanks for the solution. I will fix it up.

**Comment by nicmorais** [comment]
So, it seems like my issue was not fixed... Also, the there's a city named "Poselok Turisticheskogo pansionata "Klyazminskoe vodohranilische"" in Russia, can't we shorten this?

**Comment by dr5hn** [comment]
@nicmorais Guilers is being exported.

What about these city names? Do you have a solution for these as well?

**Comment by nicmorais** [comment]
Ok.
Translating that name to English it says "Settlement of the Tourist Boarding House "Klyazminskoe Reservoir"". We could just leave this as "Poselok "Klyaz'minskoye vodokhranilishche"" or similar... If so, the longest city name will have 59 characters, then you can also edit the SQL file to make it create a table with a smaller field for the cities names.

**Comment by dr5hn** [comment]
@nicmorais Fixed in https://github.com/dr5hn/countries-states-cities-database/commit/cd5876fb73e31f95374974a50542e5ab091329d9
