### ISSUE TITLE
Add abbreviations to states and adding zip/postal codes

### ISSUE THREAD

**Issue by ZigZapps** [dr5hn/countries-states-cities-database#3]
First of, I'd like to thank you for this great list. it would be great to add states abbreviations as well as postal/zip codes for each city if applicable. I know the list will grow big, but it can be handled through bunch of API calls to size it down.

**Comment by dr5hn** [comment]
@ZigZapps Appreciate your suggestions.
I can assure you about the state abbreviations. but it will be little difficult to add postal/zip codes.
Anyways, i will try my best to integrate your suggestions ASAP.

Thanks.

**Comment by dr5hn** [comment]
@ZigZapps Can you check now ?? I've fixed them all..

**Comment by dr5hn** [comment]
@ZigZapps closing this issue. As its already fixed now
