### ISSUE TITLE
Missing Town in NJ

### ISSUE THREAD

**Issue by Bazoqa** [dr5hn/countries-states-cities-database#312]
Hello,

There is a town missing in your data set, Mantua Township, NJ, USA. (https://en.wikipedia.org/wiki/Mantua_Township,_New_Jersey) 

Would appreciate it if you could add it to your database soon, thank you for all the hard work!

**Comment by dr5hn** [comment]
@Bazoqa Thanks for reporting 🎉 

Will take a look at it soon.
