### ISSUE TITLE
Missing States in GHANA (GH)

### ISSUE THREAD

**Issue by LawrenceAddo** [dr5hn/countries-states-cities-database#313]
States in Ghana have been updated from 10 to 16, with the new states as follows;
1. Greater Accra Region
2. Central Region 
3. The Eastern Region 
4. Western Region 
5. Ashanti Region 
6. Northern Region 
7. Upper East Region 
8. Upper West Region 
9. Volta Region Read 
10. Brong Ahafo Region 
11. Oti Region Read  **>Cities>>**Biakoye, Nkonya Ahenkro, Jasikan, Kadjebi, Krachi East, Krachi West, Nkwanta North, Nkwanta South 
12. Western North Region **>Cities>>** Aowin Municipal, Bia East, Bia West, Bodi, Juabeso, Sefwi Akontombra, Sefwi Bibiani-Anhwiaso-Bekwai, Sefwi-Wiawso, Suaman 
13. North East Region  **>Cities>>** East Mamprusi Municipality, West Mamprusi Municipality, Bunkpurugu-Nyakpanduri, Yunyoo-Nasuan, Mamprugu Moagduri, Chereponi District Assemblies 
14. Savannah Region  **>Cities>>** Bole, North Gonja, Sawla-Tuna-Kalba, West Gonja, East Gonja Municipality, Central Gonja 
15. Bono East Region **>Cities>>** Techiman Municipality, Techiman North, Atebubu-Amantin, Kintampo North Municipality, Kintampo South, Nkoranza North, Nkoranza South, Pru West, Pru East, Sene West, Sene East 
16. Ahafo Region **>Cities>>** Tano South Municipality, Tano North Municipality, Asunafo North, Asunafo South, Asutifi North, Asutifi South 

The first 10 States maintain ttheir cities. 
The cities foe the additional 6 are included above

I hope this helps

**Comment by dr5hn** [comment]
@LawrenceAddo Update is in progress.
