### ISSUE TITLE
Some Parts of the Philippines are missing some places 

### ISSUE THREAD

**Issue by francis150** [dr5hn/countries-states-cities-database#314]
Hi, Thanks for creating this wonderful and useful API. I just noticed that some places in the Philippines are missing and some states have wrong cities.
Would love to help out on this since this is where I'm from. Let me know. 😊
Thanks! 👋

**Comment by rickygzz** [comment]
Could you state which ones?

**Comment by dr5hn** [comment]
Closing this as #288 has a similar concern.
However, #288 is More precise of what list to follow.

@francis150 Please follow #288
