### ISSUE TITLE
Cities of Basel-Stadt State in Switzerland

### ISSUE THREAD

**Issue by Yekbun** [dr5hn/countries-states-cities-database#324]
Hello,
There are no city associated  with Basel-Stadt . According Wikipedia there are 3 items 

- Basel
- Bettingen
- Riehen

INSERT INTO `cities` (`id`, `name`, `state_id`, `state_code`, `country_id`, `country_code`, `latitude`, `longitude`, `created_at`, `updated_at`, `flag`, `wikiDataId`) VALUES
(149067, 'Basel', 4957, 'BS', 214, 'CH', '47.554722', '7.590556', null, null, 1, null),
(149068, 'Bettingen', 4957, 'BS', 214, 'CH', '47.571389', '7.664167', null, null, 1, null),
(149069, 'Riehen', 4957, 'BS', 214, 'CH', '47.583333', '7.633333', null, null, 1, null);

**Comment by dr5hn** [comment]
@Yekbun Thanks for reporting. 🎉 

This is awesome, will add them soon.

**Comment by dr5hn** [comment]
@Yekbun Fixed in https://github.com/dr5hn/countries-states-cities-database/commit/82f2891085e4e20d123a095187a8959175d70b4f
