### ISSUE TITLE
Keelung is not a Chinese province, it is just a city

### ISSUE THREAD

**Issue by getandplay** [dr5hn/countries-states-cities-database#325]
Keelung is not a Chinese province, it is just a city.
![image](https://user-images.githubusercontent.com/3829760/140171562-8c48a587-6e36-49e2-b9dc-1d9063fb82e9.png)

**Comment by dr5hn** [comment]
@getandplay Thanks for reporting 🎉 

I will take a look at it soon.

**Comment by dr5hn** [comment]
@getandplay 
* Removed Keelung from China province and Added it to Taiwan.
* Added missing Tianjin municipality to China & its cities
