### ISSUE TITLE
Nicaragua departament missing

### ISSUE THREAD

**Issue by edgewl2** [dr5hn/countries-states-cities-database#328]
I was checking the files, and I didn't find Nueva Segovia Departament of Nicaragua.

The departament  has 12 municipalities:
1. Ciudad Antigua
2. Dipilto
3. El Jícaro
4. Jalapa
5. Macuelizo
6. Mozonte
7. Murra
8. Ocotal
9. Quilalí
10. San Fernando
11. Santa María
12. Wiwilí

**Comment by dr5hn** [comment]
@edgewl2 Thanks for reporting. 🎉 

Fixed in https://github.com/dr5hn/countries-states-cities-database/commit/2c1844161d8ca416504642640b425893a0350bc0

**Comment by edgewl2** [comment]
Thanks to you  @dr5hn! 😀
