### ISSUE TITLE
Karnatka states city name spelling need to be corrected

### ISSUE THREAD

**Issue by ValueHome** [dr5hn/countries-states-cities-database#333]
Great effort sir... keep going.

Cities names need to be corrected, details are below:

Country: India
State: Karnataka

Cities name to be changed as below:
Bangalore as Bengaluru (Bengaluru Rural; Bengaluru Urban)
Mangalore as Mangaluru
Mysore as Mysuru
Bellary as Ballary
Bijapur as Vijayapura
Belgaum as Belagavi
Chickmagalur as Chikkamagaluru
Hubli as Hubballi
Gulbarga as Kalaburgi
Tumkur as Tumakuru

**Comment by dr5hn** [comment]
@ValueHome Please don't call me sir! I am just 29!

Thanks for reporting. 🎉 Will correct them soon!

**Comment by ValueHome** [comment]
if you need, I can help in updating this.
