### ISSUE TITLE
Missing Rosebery Australia City in New South Wales

### ISSUE THREAD

**Issue by Shashi-GS** [dr5hn/countries-states-cities-database#334]
Could you please add the city Rosebery to New South Wales Australia?

https://en.wikipedia.org/wiki/Rosebery,_New_South_Wales

I am listing out some more. Probably will post those later.

How long it will take to reflect in the REST API services?

--
Thanks,
Shashi

**Comment by dr5hn** [comment]
@Shashi-GS Thanks for reporting. 🎉 

Will get it added soon. 

Re: API 
I usually do it once in 4 months, not sure when will I do it next.

You can fetch from this Repo once updated.

**Comment by Shashi-GS** [comment]
Thank You for quick response. We found one more city is missing. 
https://en.wikipedia.org/wiki/Yallah,_New_South_Wales

As we have used this service in our production. Is it possible to deploy early, these changes?

**Comment by dr5hn** [comment]
@Shashi-GS Updated the DB in Rest API. Cheers \m/

**Comment by Shashi-GS** [comment]
Thank You, 

We found some more suburbs missing. Please add these two as well to new south wales.

Banksmeadow : 

https://en.wikipedia.org/wiki/Banksmeadow


Whale Beach:
https://en.wikipedia.org/wiki/Whale_Beach,_New_South_Wales
