### ISSUE TITLE
City Mismatch

### ISSUE THREAD

**Issue by Steevoh120** [dr5hn/countries-states-cities-database#338]
In Kenya, Thika is in Kiambu County not Nairobi County. Thika is one of the biggest Towns in Kenya, and this causes confusion among, I realized so many people in my database are in Thika but the county is incorrectly Labelled. Kindly fix this for future users

**Comment by dr5hn** [comment]
@Steevoh120 Ok thanks for reporting. 🎉 

Will take a look at it soon.
