### ISSUE TITLE
States/Regions in France

### ISSUE THREAD

**Issue by josegabrielcruz** [dr5hn/countries-states-cities-database#339]
There seems to be some issues with the state/region data for France. For instance, some cities (like Paris) appear in the response data. Also, according to this wikipedia page: [https://en.wikipedia.org/wiki/Regions_of_France](url), there are only 18 regions in France. But the response for that request returns a lot more entries than that.

**Comment by dr5hn** [comment]
@josegabrielcruz Thanks for reporting. 🎉 

Usually, I grab data from ISO official site here.
https://www.iso.org/obp/ui/#iso:code:3166:FR

It contains a mixture of following subdivisions
95 metropolitan department (en) / département métropolitain (fr)
12 metropolitan region (en) / région métropolitaine (fr)
1 dependency (en) / dépendance (fr)
5 overseas collectivity (en) / collectivité d'outre-mer (fr)
3 metropolitan collectivity with special status (en) / collectivité métropolitaine à statut particulier (fr)
1 overseas collectivity with special status (en) / collectivité d’outre-mer à statut particulier (fr)
1 overseas territory (en) / territoire d'outre-mer (fr)
1 European collectivity (en) / collectivité européenne (fr)
2 overseas unique territorial collectivity (en) / collectivité territoriale unique d'outre-mer (fr)
3 overseas departmental collectivity (en) / collectivité départementale d'outre-mer (fr)

I've recently added a column `type` in the states table. which will justify the type of states. 

Note: `type` column update is still pending for France.

**Comment by josegabrielcruz** [comment]
I see. So once the `type` is added I should be able to use it as a filter, correct?

**Comment by dr5hn** [comment]
@josegabrielcruz Yes, correct.
