### ISSUE TITLE
Banksmeadow  and Whale Beach of NSW Australia is missing.

### ISSUE THREAD

**Issue by Shashi-GS** [dr5hn/countries-states-cities-database#345]
Thank You, 

We found some more suburbs missing. Please add these two as well to new south wales.

Banksmeadow : 

https://en.wikipedia.org/wiki/Banksmeadow

Whale Beach:
https://en.wikipedia.org/wiki/Whale_Beach,_New_South_Wales

**Comment by dr5hn** [comment]
@Shashi-GS Thanks for reporting. 🎉 

Will take a look at it soon!

**Comment by Shashi-GS** [comment]
@dr5hn , It is really helpful if you can do it quickly. We are using the service as part of the production. Is there any way I can help you guys to do these missing things?

**Comment by dr5hn** [comment]
@Shashi-GS Unfortunately i am on holiday until next 2 weeks. These updates will be done in Mid January Next Year.

I don't usually update API service too frequently as it affects api performance.
