### ISSUE TITLE
Images for states and cities required.

### ISSUE THREAD

**Issue by Shiba-Kar** [dr5hn/countries-states-cities-database#348]

**Comment by dr5hn** [comment]
@Shiba-Kar Can you please elaborate on what sort of images you require?

**Comment by Shiba-Kar** [comment]
> @Shiba-Kar Can you please elaborate on what sort of images you require?

Placeholder images for cities and states...

**Comment by dr5hn** [comment]
@Shiba-Kar I still don't understand can you please explain your use case?

**Comment by dr5hn** [comment]
Closing until answered.
