### ISSUE TITLE
Accents

### ISSUE THREAD

**Issue by jessequinn** [dr5hn/countries-states-cities-database#35]
Good work here,

Just one thing, I have noticed many of the accents are not showing correctly. Is this just me or there is an issue with the encoding? I am referring to the SQL files, for instance, `cities.sql`.

**Comment by dr5hn** [comment]
@jessequinn 

So in sql the unicode characters are encoded according to mysql requirements. Don't worry.. When you try to read or compare data from sql. It will work fine.

**Comment by jessequinn** [comment]
that is what is interesting using the `world.sql` and ` * @ORM\Table(options={"collate"="utf8_general_ci"})` as symfony 4 doctrine annotations it appears wrong.

**Comment by dr5hn** [comment]
@jessequinn 
Any update on this ? Is everything fine or needs corrections ?

**Comment by jessequinn** [comment]
i ended up having to use the json file to build the tables. regardless of what i did, i always had symbols show with error.

**Comment by dr5hn** [comment]
Ok good to close then. Thanks @jessequinn
