### ISSUE TITLE
Wrong WikiDataIds for some cities

### ISSUE THREAD

**Issue by evancampbell** [dr5hn/countries-states-cities-database#352]
There are cases where the wikiDataId is just not correct. For some reason this seems to vary by the country. Italy for example has lots of these issues. The city of Naples:

140713,Naples,1669,72,Campania,107,IT,Italy,40.85216000,14.26811000,Q30028139

Q30028139 points to the village of Nanno.

Bangladesh is another problem country. This time, many of the Ids will instead point to the district or municipality the city is in, rather than the city itself. Dhaka's id, Q1850485, points to Dhaka District. This is an issue when trying to get statistics about cities, like population.

**Comment by dr5hn** [comment]
@evancampbell Thanks for reporting.

However, it has been already reported by someone else long ago. So it's kind of a known issue and will resolve slowly.

Duplicate #185 

Hence closing.
