### ISSUE TITLE
In Egypt, There is a state that does not exist

### ISSUE THREAD

**Issue by moolotfy** [dr5hn/countries-states-cities-database#359]
In Egypt, there are only 26 governorates out of 27, please add the Sharqiyah governorate 'State' quickly thanks for understanding
![image](https://user-images.githubusercontent.com/62478801/148686095-21a14f70-a603-4a4d-9539-5c80b11b3a68.png)

**Comment by dr5hn** [comment]
@moolotfy Thanks for reporting. 🎉 

Will take a look at it soon.

**Comment by moolotfy** [comment]
@dr5hn Thanks, Please do this quickly because customers of this state are unable to register,
BR,
Thanks.

**Comment by dr5hn** [comment]
@moolotfy I will try to fix this ASAP.

**Comment by moolotfy** [comment]
@dr5hn Thanks
