### ISSUE TITLE
Missing Jalisco state of Mexico | id: 142

### ISSUE THREAD

**Issue by abielmagu** [dr5hn/countries-states-cities-database#36]
Hi friend!! tnks a lot for this database, only missing the state of Jalisco with its cities... tnks again!

**Comment by tjaoc** [comment]
Jalisco not appear

**Comment by vistaar-dgada** [comment]
@tjaoc @abielmagu Thanks for reporting. Will try to fix it soon.

**Comment by dr5hn** [comment]
@tjaoc @abielmagu Thanks for reporting. Will try to fix it soon.

**Comment by dr5hn** [comment]
@tjaoc @abielmagu Fixed in #83
