### ISSUE TITLE
JSON and CSV Country Table does not contain "wikiDataId"

### ISSUE THREAD

**Issue by Freelenzer** [dr5hn/countries-states-cities-database#362]
The countries.json and countries.csv files do not contain any "wikiDataId" while the cities.json has some.

The countries.sql files contains that data.

Is there any way to add this data to the json file?

**Comment by dr5hn** [comment]
@Freelenzer Purposely not added due to limit the sizes of file.

However, you can edit the code and generate them using this file.
https://github.com/dr5hn/countries-states-cities-database/blob/master/scripts/export.php
