### ISSUE TITLE
Make the contributing guidelines more useful

### ISSUE THREAD

**Issue by braaar** [dr5hn/countries-states-cities-database#364]
I'm currently taking a stab at correcting the data for Norwegian states (or counties as we call them in Norway) from #207 

I'm finding it a little hard to understand exactly how I am meant to source some of the data. It's not clear what the lat/long coordinates are supposed to represent. WikiDataId is fair enough.

I suggest we make some tables that explain the fields. Some of this information seems to exist on the [API docs](https://countrystatecity.in/docs/api/state/), but it doesn't cover all the columns as far as I can see.

Here's a start for states.sql:

| Column | Data type | Explanation | 
| ----------------- | --------------- | -------------- |
| `id` | integer | Unique ID used internally, just increment by one when adding entries to the list. |
| `name` | string | The official name of the state. Use WikiData or Wikipedia or some other legitimate source. |
| `country_id` | integer | Unique id of parent country from `countries.sql` |
| `country_code` | string | [ISO3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code of the parent country | 
| `fips_code` | |  ISO-3166-2 subdivision code for the state. Can be found in wikipedia articles such as this: [ISO_3166-2:NO](https://en.wikipedia.org/wiki/ISO_3166-2:NO). [FIPS county codes](https://en.wikipedia.org/wiki/FIPS_county_code) were deprecated in 2008, so surely we aren't using them? |
| `latitude` | float | Where do we get this from? |
| `longitude` | float | Where do we get this from? |
| `created_at` | | Is this automatically set? |
| `updated_at` | | Is this automatically set? |
| `flag`| | |
| `wikiDataId` | string | The unique ID for this state on wikiData |

What do you think about adding some quick reference tables like this?

**Comment by dr5hn** [comment]
@braaar Thanks for the suggestions. 🎉 

This is awesome. Sure, please go ahead and add it in https://github.com/dr5hn/countries-states-cities-database/blob/master/.github/CONTRIBUTING.md. 

Answers to your query:
* I have to fill up `created_at` with `NOW()`.
* the `updated_at` fills up automatically.
* `latitude` and `longitude` I search for that location in Google maps, copy the lat and long from the URL and paste it into MySQL Workbench / TablePlus / sequel ace.
* `country_code` and `state_code` i grab it from here. https://www.iso.org/obp/ui/#iso:code:3166:NO

Please let me know if you have any other queries. Happy to help.

**Comment by dr5hn** [comment]
@braaar Can you please review the PR?

**Comment by braaar** [comment]
@dr5hn I have actually been working on my own version of this. https://github.com/dr5hn/countries-states-cities-database/pull/384

**Comment by dr5hn** [comment]
@braaar Oh, I see! Ok, no problem.

**Comment by dr5hn** [comment]
Done. Updated. https://github.com/dr5hn/countries-states-cities-database/blob/master/.github/CONTRIBUTING.md
