### ISSUE TITLE
United kingdom data is wrong

### ISSUE THREAD

**Issue by ArsooCh** [dr5hn/countries-states-cities-database#37]
Some thing is wrong with the United kingdom data. All states have the same cities. Cities and States are also wrong. Check screenshot

**Comment by ArsooCh** [comment]
![2019-11-05_1509](https://user-images.githubusercontent.com/35623602/68199040-0baa2280-ffdf-11e9-8ef2-9416a8fdd40e.png)

**Comment by jonasmarco** [comment]
No news, I really needed this complete? : /

**Comment by dr5hn** [comment]
@jonasmarco It's already fixed. Can you please check now ?

**Comment by jonasmarco** [comment]
> @jonasmarco Acabei de verificar que não está consertado. Irá corrigir isso em breve.

@dr5hn  Easy guy, thanks for the reply.

I would like to know how you do the work with this data? Do you use any tools to facilitate the visualization and manipulation of data?

I ask that for those who also know that I cannot contribute with the data.

You could include this information in README.md.

**Comment by dr5hn** [comment]
@jonasmarco 

> I would like to know how you do the work with this data? Do you use any tools to facilitate the visualization and manipulation of data?
As of now, I do manipulation manually. If you want to know more about it. Check the (https://github.com/dr5hn/countries-states-cities-database/tree/master/vendor)[vendor] folder.

Appreciate, If you have any ideas to making contributions much simpler.

**Comment by dr5hn** [comment]
@jonasmarco @ArsooCh 
Finally Fixed. 🎉
