### ISSUE TITLE
Cities SQL "state_id" Numbers are Off by 207

### ISSUE THREAD

**Issue by ProBidPro** [dr5hn/countries-states-cities-database#373]
I've installed the Country, State and Cities Database's using the "SQL" inserts and re-combined it together into 1 Database Table for my needs, but in doing so I discovered that all the "state_id" numbers in the "cities" Table are off by 207. 

Adding 207 to the original "state_id" re-aligns all the Cities correctly to the proper States.

Example: 123444, 'Oliver Springs', 1454, 'TN', 233, 'US', ....

Should Be: 123444, 'Oliver Springs', 1661, 'TN', 233, 'US', ....

Kevin

**Comment by dr5hn** [comment]
@ProBidPro Thanks for reporting. 🎉 

Will take a look at it soon.

**Comment by dr5hn** [comment]
@ProBidPro 1454 is the correct state_id. 
Cause state with 1661 belongs to Switzerland
