### ISSUE TITLE
Cambodia does not have state

### ISSUE THREAD

**Issue by soeurngsar** [dr5hn/countries-states-cities-database#375]
For a country like Cambodia, it does not have the state and all the state that you store it just the province.
Some provinces can be called city as well e.g. Battambang province we can call Battambang city also.

Please study this situation and correct it.

Thank for your hard work,

**Comment by dr5hn** [comment]
@soeurngsar Thanks for reporting. 🎉 

That's a bit tricky to handle. However, the overall goal of the project is to maintain 3 levels of data and discard the 4th level.
Let me know if your findings fit this philosophy.

**Comment by soeurngsar** [comment]
Thank for your time, if you want to keep tree level of the data please note that some countries doesn't have state in that case state is empty and move the state level to city level. I'm sure that many countries in ASEAN follow this rules.

**Comment by braaar** [comment]
Canada doesn't have states, it has provinces and territories. The state level in this project is used to represent Provinces such as Ontario, British Columbia, etc.
 
Norway doesn't have states, it has counties. The state level in this project is used to represent counties in Norway like Agder and Nordland.

Cambodia's 24 (de facto 25) provinces seems like a perfect fit for the state category in my view. [The province of Battambang](https://en.wikipedia.org/wiki/Battambang_province) belongs in that category just as [Battambang city](https://en.wikipedia.org/wiki/Battambang) belongs in the city category. 

We have the same in Norway, where the capital of Oslo is a county and also a city (it is also a municipality but that level doesn't exist in this project).

It would be very misleading to leave the state level empty for cambodia. The provinces clearly fit into that category just like they do for Canada or Norway.

**Comment by dr5hn** [comment]
@soeurngsar We can't leave state-level empty as MySQL is a relational database. We have to maintain a parent-child relationship.

In order to fix this type of issue, we've added a column `type` in the state. Which justifies what type of record it is.

I think putting them into the `states` table and filling the `type` column will justify the data.

https://iso.org/obp/ui/#iso:code:3166:KH

**Comment by soeurngsar** [comment]
Ok, thank for your recommendation.
I will follow your rules then.
