### ISSUE TITLE
Brazil: "Amazonas" and "Santa Catarina" states do not have lat/lng

### ISSUE THREAD

**Issue by joaorb64** [dr5hn/countries-states-cities-database#376]
I'm not sure on how to contribute on this one, but I noticed this data is missing.
If there's any default procedure for this, please let me know and I'll go for a PR!

**Comment by dr5hn** [comment]
@joaorb64 Here you go!
https://github.com/dr5hn/countries-states-cities-database/blob/master/.github/CONTRIBUTING.md

**Comment by joaorb64** [comment]
Done! https://github.com/dr5hn/countries-states-cities-database/pull/377 :)
