### ISSUE TITLE
American Samoa appears as State inside United States

### ISSUE THREAD

**Issue by the-douglas-soares** [dr5hn/countries-states-cities-database#378]
American Samoa appears as a country and as State inside United States

![image](https://user-images.githubusercontent.com/4245622/151405058-28ffb40c-8a55-4b8f-9560-5dd72f8db733.png)

**Comment by dr5hn** [comment]
@the-douglas-soares Thanks for reporting. 🎉 

Btw, which one is correct?

**Comment by babyrusa** [comment]
I believe Samoa is a US's territory. So I think it makes sense if it falls under "states and territories"

**Comment by dr5hn** [comment]
@the-douglas-soares Yes, it's correct according to the Official ISO Website.
https://www.iso.org/obp/ui/#iso:code:3166:US
