### ISSUE TITLE
Why is everything duplicated?

### ISSUE THREAD

**Issue by braaar** [dr5hn/countries-states-cities-database#379]
It seems like a poor choice to duplicate all the SQL source code by having the same stuff in eg. `cities.sql` and `world.sql`. 

Why is that a thing?

**Comment by dr5hn** [comment]
@braaar If you see the `world.sql` file closely it has SQL queries for all 3 tables together. And `cities.sql` has only a cities table.

**Comment by braaar** [comment]
> @braaar If you see the `world.sql` file closely it has SQL queries for all 3 tables together. And `cities.sql` has only a cities table.

The way I see it, `world.sql` basically contains all the contents of `cities.sql`, `states.sql` and `countries.sql` added together. So why are we writing all the source code twice?

**Comment by dr5hn** [comment]
@braaar I've purposely kept the standalone files as well. For ex: if the user wants only `countries` data then he can directly grab `countries.sql`.

Similarly, if he needs only `countries and states` he can grab `countries.sql` and `states.sql`. Likewise for `countries and cities` as well.

**Comment by braaar** [comment]
Would it not be possible with some tooling to set it up so that we only need to make changes in once file, and the other file(s) can be generated by a script (for example in a github action)?

**Comment by dr5hn** [comment]
Awesome idea! Never imagined it.

Yes it can be done. I will get it implemented.

Thanks

**Comment by ZenithClown** [comment]
This will also help in keeping all the updated information in one place, and everything can be automated from there!!
