### ISSUE TITLE
Puerto Rico States are missing

### ISSUE THREAD

**Issue by rikr2sanchez** [dr5hn/countries-states-cities-database#380]
![image](https://user-images.githubusercontent.com/19697749/151637919-2d8fde84-6d96-4137-bcc6-796cee1d604a.png)

**Comment by dr5hn** [comment]
@rikr2sanchez Thanks for reporting. 🎉 

I will take a look at it soon.

**Comment by fabiuhp** [comment]
Inside the database already have the data about Puerto Rico. Puerto Rico is a state of USA.
