### ISSUE TITLE
Request an API Key

### ISSUE THREAD

**Issue by yyyyy1111122** [dr5hn/countries-states-cities-database#390]
I submitted an API key request 5 days ago, but you didn't submit it. When will you send the key?

**Comment by dr5hn** [comment]
@yyyyy11111122 What's your email?..

**Comment by yyyyy1111122** [comment]
wwweb2401@gmail.com

**Comment by dr5hn** [comment]
Hope you have received key now

**Comment by yyyyy1111122** [comment]
Yes. Thank you
