### ISSUE TITLE
Some States have 'wikiDataId' value MANUAL

### ISSUE THREAD

**Issue by Freelenzer** [dr5hn/countries-states-cities-database#393]
4852	Ladakh	
4862	Hamilton Municipality	
4865	Saint George's Municipality	
4880	Ciudad Autónoma de Buenos Aires

Have the wikiDataId set to "MANUAL" what does that mean?
Is this a bug or where does this data come from?

Thanks in advance. I really would like to help improve this project :)

**Comment by dr5hn** [comment]
@Freelenzer I was keeping that in my earlier developments of this database. Not needed anymore. I will replace them with the actuals soon.
