### ISSUE TITLE
Remove tab characters from data

### ISSUE THREAD

**Issue by octocat-1** [dr5hn/countries-states-cities-database#395]
Please remove the tab characters `\t` from data

"id": 3636
"name": "San Luis\t"

"id": 2278
"type": "autonomous region\t"

"id": 2267
"type": "special administrative region\t"

"id": 2269
"type": "autonomous region\t"

"id": 2262
"type": "autonomous region\t"

"id": 4921
"type": "capital district\t"

"id": 5035
"name": "Bas-Rhin\t"

"id": 5055
"name": "Haute-Vienne\t"

"id": 4971
"name": "Hautes-Alpes\t"

"id": 5062
"name": "Val-de-Marne\t"

"id": 951
"type": "autonomous region\t"

"id": 4964
"name": "Nueva Segovia\t"

"id": 952
"type": "autonomous region\t"

"id": 3412
"type": "special municipality\t"

"id": 4966
"type": "special municipality\t"

"id": 3406
"type": "special municipality\t"

"id": 3421
"type": "special municipality\t"

"id": 3422
"type": "special municipality\t"

"id": 3419
"type": "special municipality\t"

**Comment by dr5hn** [comment]
@octocat-1 Sure, will fix it ASAP.
