### ISSUE TITLE
Sweden duplicate cities

### ISSUE THREAD

**Issue by scriptcoded** [dr5hn/countries-states-cities-database#396]
Hi there, what a wonderful repo :tada: Good job!

I noticed that the list of Swedish cities has quite a few duplicates. To be precise, many Swedish cities have municipalities with the same name, and they seem to have gotten into the list as well. Here's an example:

("kommun" = "municipality")

- Lund
- Lunds Kommun
- Åstorp
- Åstorps Kommun
- Kävlinge
- Kävlinge Kommun

We'll just remove the ` Kommun` suffixed rows in our DB. Perhaps the same could be done here, as it seems that all the municipalities have their cities in the list as well.

/Malcolm

**Comment by dr5hn** [comment]
@scriptcoded Fixed.
