### ISSUE TITLE
England?

### ISSUE THREAD

**Issue by macsobczyk** [dr5hn/countries-states-cities-database#4]

**Comment by macsobczyk** [comment]
Check the cities and states belonging to country number 232 (UK). There's Manchester, London, Edinburgh and other famous big cities of England but all of them belong to United States (country number 233) or others.

**Comment by dr5hn** [comment]
@macsobczyk ok will look in to it.

**Comment by dr5hn** [comment]
@macsobczyk Can you check now ?? I've fixed them all..

**Comment by macsobczyk** [comment]
@dr5hn Both cities and states look good. Thank you.

**Comment by dr5hn** [comment]
Hence Solved.
