### ISSUE TITLE
State details not found error for Iran States

### ISSUE THREAD

**Issue by MostafaMobed** [dr5hn/countries-states-cities-database#406]
Hi, Thank you for your useful API.
Issue:
Get all Cities by state is ok but calling detail of same state : 404: error: "No State/Region Found."

https://api.countrystatecity.in/v1/countries/IR/states/23/cities --> 200OK
https://api.countrystatecity.in/v1/countries/IR/states/23 --> 404

**Comment by dr5hn** [comment]
@MostafaMobed Thanks for reporting. Will fix it ASAP.

**Comment by MostafaMobed** [comment]
@dr5hn Thanks

**Comment by dr5hn** [comment]
@MostafaMobed This has been fixed. 🎉
