### ISSUE TITLE
countries-states-cities-database/sql/cities.sql upload error

### ISSUE THREAD

**Issue by Sujon-Ahmed** [dr5hn/countries-states-cities-database#412]
When I import the cities.sql file in the local PHPMyAdmin database file then it's not uploaded completely!

![Screenshot_3](https://user-images.githubusercontent.com/51746242/158077155-7ce818d8-9859-4e97-8695-6e4b60b7cdf2.png)

**Comment by dr5hn** [comment]
@Sujon-Ahmed 
Instead of drag and drop can you please try to upload via choose file and let me know the exact error with the screenshot?

**Comment by Sujon-Ahmed** [comment]
> @Sujon-Ahmed Instead of drag and drop can you please try to upload via choose file and let me know the exact error with the screenshot?

**Comment by Sujon-Ahmed** [comment]
when I try to upload via choose file then given an error like this!
[image: Screenshot_5.png]
[image: Screenshot_4.png]

**Comment by dr5hn** [comment]
@Sujon-Ahmed You need to drop all tables first and re-import `world.sql` I believe it's an error of foreign keys.
