### ISSUE TITLE
Malaga Australia suburb is missing.

### ISSUE THREAD

**Issue by Shashi-GS** [dr5hn/countries-states-cities-database#415]
@dr5hn ,

Could you please help me with the ticket : https://github.com/dr5hn/countries-states-cities-database/issues/385#issue-1120257661

one more sub urb is missing : 

https://en.wikipedia.org/wiki/Malaga,_Western_Australia

As we are using this in production. Is it possible to give the changes sooner?

Thanks in Advance,
Shashi

**Comment by dr5hn** [comment]
@Shashi-GS Thanks for reporting. 🎉 
I will add it ASAP.

Please read this:
![Screenshot 2022-03-17 at 10 32 49 AM](https://user-images.githubusercontent.com/6929121/158740807-5c4023f3-c947-4131-85e5-bb793c0a084f.png)
