### ISSUE TITLE
Missing a city in Ukraine

### ISSUE THREAD

**Issue by steminist-ua** [dr5hn/countries-states-cities-database#416]
Hi, thanks for this amazing library!

Kremenchuk city (Countries: Ukraine, States: Poltavska oblast) is missing. 
But there is a city in the demo: https://dr5hn.github.io/countries-states-cities-database/

{"id": 149432,
  "name": "Kremenchuk",
  "state_id": 5071,
  "state_code": "53",
  "state_name": "Poltavska oblast",
  "country_id": 230,
  "country_code": "UA",
  "country_name": "Ukraine",
  "latitude": "49.07750000",
  "longitude": "33.42388889",
  "wikiDataId": "Q156724"}

**Comment by dr5hn** [comment]
@steminist-ua I've updated the API database to the latest.
