### ISSUE TITLE
Problem with "Get the list of cities in a state"

### ISSUE THREAD

**Issue by Baldoma** [dr5hn/countries-states-cities-database#417]
I want to view cities of "Province of Ravenna" in "Italy", but result is empty.
in cities.sql data may be correct, this is an example
(138403,'Faenza',1773,'45',107,'IT',44.29007000,11.87948000,'2019-10-06 01:09:32','2019-10-06 01:09:32',1,'Q989795')

this is my query
https://api.countrystatecity.in/v1/countries/it/states/ra/cities

**Comment by dr5hn** [comment]
@Baldoma Thanks for reporting. 🎉 

Currently, there are no cities attached to the "Province of Ravenna" in DB. I will add them soon and let you know.

**Comment by dr5hn** [comment]
@Baldoma Have added missing cities to "Province of Ravenna".
