### ISSUE TITLE
Flag are not coming on the new browser versions

### ISSUE THREAD

**Issue by neerajsharma-kiwi** [dr5hn/countries-states-cities-database#418]
99.0.4844.82 chrome windows os flags are not rendered only the country abbreviation is coming.

**Comment by dr5hn** [comment]
@neerajsharma-kiwi

I am on
<img width="383" alt="Screenshot 2022-03-23 at 5 35 36 PM" src="https://user-images.githubusercontent.com/6929121/159695241-42ad0b87-32f3-4e74-af79-c6f55a63fd2b.png">

and i can see the flags.
<img width="412" alt="Screenshot 2022-03-23 at 5 35 14 PM" src="https://user-images.githubusercontent.com/6929121/159695179-8a6ef39f-bf0c-49e2-85a7-5ae3c5afea35.png">

**Comment by amanpoplify** [comment]
<img width="364" alt="Screenshot 2024-06-12 at 2 27 19 PM" src="https://github.com/dr5hn/countries-states-cities-database/assets/10806918/89391709-fa58-4b16-a87b-d64c1229cf10">
This is how Flags are showing in chrome windows
