### ISSUE TITLE
Australia suburbs are missing!

### ISSUE THREAD

**Issue by Shashi-GS** [dr5hn/countries-states-cities-database#419]
Could you please add these missing suburbs?
![image](https://user-images.githubusercontent.com/17082069/159845210-7317fde1-11ae-4bd5-8a93-c23f5dabf00d.png)

**Comment by Shashi-GS** [comment]
@dr5hn , At least only this time, can you please deploy these changes ASAP? our customer escalated this issue very badly.  

Thanks In Advance, 
Shashi

**Comment by dr5hn** [comment]
@Shashi-GS Sure, I will fix that by tomorrow and update the DB in live as well.

But only this time.
