### ISSUE TITLE
Thornhill - Ontario Missing

### ISSUE THREAD

**Issue by bimaldave** [dr5hn/countries-states-cities-database#422]
Hi,

Thornhill, Ontario, Canada is missing:

https://en.wikipedia.org/wiki/Thornhill,_Ontario

**Comment by dr5hn** [comment]
@bimaldave Thanks for reporting. 🎉 

I will add it soon!

**Comment by dr5hn** [comment]
@bimaldave Have added the missing Thornhill to Ontario.
