### ISSUE TITLE
Bug: Croatia "Karlovac County" and "Varaždin County" have wrongly the same state_code="05"

### ISSUE THREAD

**Issue by boa86** [dr5hn/countries-states-cities-database#423]
Hi,

Croatia "Karlovac County" and "Varaždin County" have the same state_code="05"
`{
                "id": 5069,
                "name": "Karlovac County",
                "state_code": "05",
                "latitude": "45.26133520",
                "longitude": "15.52542016",
                "type": null,
                "cities": []
            },`

`            {
                "id": 739,
                "name": "Varaždin County",
                "state_code": "05",
                "latitude": "46.23174730",
                "longitude": "16.33605590",
                "type": null`

Accordingly to Wiki,  "Karlovac County" has state code "04" (ISO 3166 code HR-04)

https://en.wikipedia.org/wiki/Vara%C5%BEdin_County
https://en.wikipedia.org/wiki/Karlovac_County

**Comment by dr5hn** [comment]
@boa86 Thanks for reporting. 🎉 

I will fix that soon!

**Comment by dr5hn** [comment]
@boa86 I have fixed the state_code of Karlovac County.
