### ISSUE TITLE
Morocco States Mixed with cities

### ISSUE THREAD

**Issue by younes-alouani** [dr5hn/countries-states-cities-database#427]
Hey dear community, 

I'm from Morocco, and I intend to use a database of cities and states of my Countries. 
I tried this one, but I found out that many states in the states.csv are indeed cities and not states. 
For exemple "Khouribga" is not a state but a city in the state of "Béni-Mellal".

**Comment by dr5hn** [comment]
@younes-alouani According to this source it looks correct to me.
https://www.iso.org/obp/ui/#iso:code:3166:MA

Subdivisions
13 prefecture (en) / préfecture (fr) / ‘amālah (ar)
62 province (en) / province (fr) / iqlīm (ar)
12 region (en) / région (fr) / jihāt (ar)

I understand your concern, In this DB we're maintaining only 3 relationships and hence you see Regions and provinces mixed up in the states table.

**Comment by dr5hn** [comment]
@younes-alouani To be more precise I have updated the `type` column under the states table to segregate the types among the states.
