### ISSUE TITLE
Large cache on hml ambient

### ISSUE THREAD

**Issue by burgodev** [dr5hn/countries-states-cities-database#428]
Heys guys, we're having performance issues using this lib. I'mean, the lib is great but we are downloading a 17mb cache, is this normal or we are doing something wrong? Can u guys help us? 

![cache country state city](https://user-images.githubusercontent.com/50026618/163189212-d5f9ad56-90b7-4c50-ba8d-4dae6cd467b0.png)
![console cuntry state city](https://user-images.githubusercontent.com/50026618/163189222-f6ee53be-1b94-4018-8de3-a8479b321881.jpg)

**Comment by dr5hn** [comment]
@burgodev Wrong repo! I am only providing the data to that npm package you're using.

I am not the owner of the npm package you're using, please submit an issue here.
https://github.com/harpreetkhalsagtbit/country-state-city
