### ISSUE TITLE
Egypt City districts

### ISSUE THREAD

**Issue by abgrxenda** [dr5hn/countries-states-cities-database#429]
the country of Egypt is list correctly, however the district areas of the city is not correct at all
for instance the major two cities are Cairo & Alexandria,
Cairo is listing only three districts only one is correct the other wrong and about 7 or 8 are missing
City of Alexandria, only one District area is listed and it is wrong, around 12 are missing

**Comment by dr5hn** [comment]
@abgrxenda Fixed in #440

**Comment by dr5hn** [comment]
@abgrxenda I have added missing districts to Cairo and Alexandria. Please check and let me know.

Feel free to reopen this ticket if issue still persist.
