### ISSUE TITLE
Counties are not Cities, Misc Stuff...

### ISSUE THREAD

**Issue by viper2kx** [dr5hn/countries-states-cities-database#43]
In cities.sql, I live in id=118291 (a county) and also live in id=121951 (city)

Also, you are missing a Minneapolis listing (KS, MN and NC...) https://en.wikipedia.org/wiki/Minneapolis,_North_Carolina

... and, in countries.sql there are places like Vatican and US Minor Outlying Islands that don't have states/"administration areas" or cities - where I am getting with this is, please add latitude and longitude to records on countries.sql and states.sql

**Comment by dr5hn** [comment]
@viper2kx It's been a long time this issue is pending.

I tried looking into it, looks solved to me. Hence closing this issue for now.

Feel free to re-open if you still face the same issue.
