### ISSUE TITLE
Hungarian states (counties) are mixed with big cities

### ISSUE THREAD

**Issue by bgabor1984** [dr5hn/countries-states-cities-database#430]
Hi,

I am Hungarian, so I would like to inform you Hungarian states (counties) list is mixed with Hungarian big cities in counties. For example: Miskolc is a city in Borsod-Abaúj-Zemplén county. Budapest which is the capital city of Hungary is part of Pest county.  

The exact list of Hungarian states (counties) are:
Bács-Kiskun county
Baranya county
Békés county
Borsod-Abaúj-Zemplén county
Csongrád-Csanád county
Fejér county
Győr-Moson-Sopron county
Hajdú-Bihar county
Heves county
Jász-Nagykun-Szolnok county
Komárom-Esztergom county
Nógrád county
Pest county
Somogy county
Szabolcs-Szatmár-Bereg county
Tolna county
Vas county
Veszprém county
Zala county

**Comment by dr5hn** [comment]
@bgabor1984 Thanks for reporting. 🎉 

However, I grab the data from the Official ISO website and it has mentioned all of them on the same level. https://www.iso.org/obp/ui/#iso:code:3166:HU

Also, some city has a county right.

Can you please check and let me know.

**Comment by dr5hn** [comment]
@bgabor1984 I have added one missing county to the Hungry. Also please feel free to re-open this ticket if you've got the reply to my previous comment.
