### ISSUE TITLE
Lat Long information is incorrect

### ISSUE THREAD

**Issue by rmsmani** [dr5hn/countries-states-cities-database#433]
HI Team

I have checked the Lat long for few cities but the information which is given in this package seems to be incorrect.

Information from this package is 

`
{
 "name": "Salem",
  "state_code": "TN",
  "country_code": "IN",
  "latitude": "11.69000000",
  "longitude": "78.29000000",
 }
`
Based on the above lat long, it goes to different place.
`But for the same location, the lat long from google maps is 11.665158753444805, 78.1520265949836`

Is there any option to fix this.

**Comment by dr5hn** [comment]
@rmsmani Thanks for reporting. 🎉 

I will fix this up. But if you find any other city with incorrect lat and long, please feel free to raise a issue.

**Comment by dr5hn** [comment]
@rmsmani I've fixed the Lat long information for Salem, Tamilnadu. Please feel free to open a new ticket if you find any more issues.
