### ISSUE TITLE
Request for API

### ISSUE THREAD

**Issue by kelbixgroup** [dr5hn/countries-states-cities-database#434]
Support,

We did apply to request for your API. could you please give us access to your api?

Your api will be integrated into our custom php system on this subdomain: https://www.securedgateway.kelbix.co.za/

Regards.
Thanks
Adeshina

**Comment by dr5hn** [comment]
Hi Ardeshina,

Can you please tell me which email you put in the form while Requesting an API?
https://countrystatecity.in/request/

These are the requests we received from 22nd April to 25th April.
<img width="378" alt="Screenshot 2022-04-29 at 12 24 12 PM" src="https://user-images.githubusercontent.com/6929121/165898189-76c4753a-05c0-4760-83e8-a7ee1564ca58.png">


Kind Regards,
Darshan Gada

**Comment by kelbixgroup** [comment]
Dear Darshan,

Our email is not on the list. 

There should be either on the list:
[systech44@gmail.com](mailto:systech44@gmail.com)
[admin@kelbix.co.za](mailto:admin@kelbix.co.za)

Moreso, we have requested again now with [admin@kelbix.co.za](mailto:admin@kelbix.co.za)
![5555](https://user-images.githubusercontent.com/1221749/165924564-8887601e-f3c1-418c-8919-d06994616311.png)

**Comment by kelbixgroup** [comment]
thanks for your support. Regards.
