### ISSUE TITLE
Netherlands municipality duplicates

### ISSUE THREAD

**Issue by KaneCohen** [dr5hn/countries-states-cities-database#435]
Hi, similar to how there were some duplicate "municipality" cities in #396 - there is a number of "Gemeente" cities for Netherlands. For example

Gemeente Amsterdam
Amsterdam

Gemeente Heerde
Heerde

and so on.

**Comment by dr5hn** [comment]
@KaneCohen Thanks for reporting. 👍🏼 

I will try to fix them soon.

**Comment by dr5hn** [comment]
@KaneCohen I have removed all duplicate cities starting with "Gemeente". Please feel free to reopen this ticket if the issue still persists.
