### ISSUE TITLE
Nuevo León, México cities outdated

### ISSUE THREAD

**Issue by Iracheta18** [dr5hn/countries-states-cities-database#437]
Hi, I realized that the cities of the state of Nuevo Leon in Mexico are a bit oudated, there're some large areas that are listed as cities and there a cities that are missing, some examples:

Jardines de la Silla (Jardines) is an area inside of the city of Guadalupe.
Apodaca, one of the largest cities is missing from the list.

I would appreciate if you could update them.

Thank you, Hugo Iracheta.

**Comment by dr5hn** [comment]
@Iracheta18 Thanks for reporting. 🎉 

Will take a look at it soon!

**Comment by dr5hn** [comment]
@Iracheta18 Have updated the Nuevo Leon cities, please feel free to open a separate issue, if you find any more states having missing cities.
