### ISSUE TITLE
For Mauritania - Nouakchott is a state but a city also 

### ISSUE THREAD

**Issue by Moomoo14** [dr5hn/countries-states-cities-database#439]
Nouakchott is a state and a city for mauritania.
it has 3 sub regions.
isssue: when i query the list of cities in maurtania Nouakchottt does not appear, but it appears on the State/province level

**Comment by dr5hn** [comment]
@Moomoo14 As per wikipedia Nouakchott is divided in to 3 subregions.
Nouakchott-Ouest
Nouakchott-Nord
Nouakchott-Sud

So under which region do you want Nouakchott city available?

**Comment by dr5hn** [comment]
@Moomoo14 Have added missing cities/towns to Nouakchott-Ouest, Nouakchott-Nord & Nouakchott-Sud

**Comment by Moomoo14** [comment]
> @Moomoo14 As per wikipedia Nouakchott is divided in to 3 subregions. Nouakchott-Ouest Nouakchott-Nord Nouakchott-Sud
> 
> So under which region do you want Nouakchott city available?

this is used in the formal manner , per reality the city is just Nouakchott with is sub region and all the other district are just called Nouakchott. it might make more sense to have one city and all of the sub regions in it.
