### ISSUE TITLE
Turkey States

### ISSUE THREAD

**Issue by Seration** [dr5hn/countries-states-cities-database#443]
There is no state system in Turkey

So the state results in the data are the cities of Turkey.
The cities in the data are the towns of the cities.

It would be great if you can fix it

**Comment by dr5hn** [comment]
@Seration I see there's a province system. Usually, I follow the official site for the data update. https://www.iso.org/obp/ui/#iso:code:3166:TR

Just FYI, All provinces will go within the state table and only 3 level structure is maintained.

Please check and let me know.

**Comment by oruchreis** [comment]
How can we distinguish city and state than? When we display this data to the end users, which label we must choose? Are there any information for countries that the state is actually city and the city is actually district? Is this only for Turkey?
