### ISSUE TITLE
UK

### ISSUE THREAD

**Issue by rokrokos** [dr5hn/countries-states-cities-database#452]

**Comment by dr5hn** [comment]
@rokrokos is Already being raised as an issue. I think the issue relates to fixing up these first.
#290 
#168 
#227

**Comment by dr5hn** [comment]
@rokrokos Because it requires a restructuring of the whole country, state and city. Might take another 6 months to fix it.

Just FYI, this database took me 4 years to build it.

Many companies use this DB in production.

**Comment by rokrokos** [comment]
Thanks, all great  - thank you for your work.

But anyway - how do companies use this DB in production? Do they let all Londons (for example) in a list? I am not complaining - I am seriously asking. Any tips?

**Comment by rokrokos** [comment]
You have a great DB, so close... it's really sad that because 1/4 of wrong data or incorrectly sorted it's almost useless in production (for example worldwide social networks, webshops).

Italy, Croatia, Slovenia, ... all have a lot of problems.

What if you divide the work among us - for example - I am from Slovenia, and I can make a complete DB of Slovenian states/cities in a week or so.

1) By the way, It would be great if you could add zip codes / postal codes for states/cities.
2) States / Cities should be generic and not like "Ljubljana City Municipality" --> "Ljubljana" or "Dravlje District" -> "Dravlje"

**Comment by dr5hn** [comment]
@rokrokos 

Yes, I know it's of no use for some people.

I will be happier if you can contribute towards making "Slovenia" more accurate.

I have a plan to add zip codes / postal codes in near future. I am just finding for the correct source of data.

About this issue, "Dravlje District" -> "Dravlje"
Yes, I am trying to fix it all one by one.

> You have a great DB, so close... it's really sad that because 1/4 of wrong data or incorrectly sorted it's almost useless in production (for example worldwide social networks, webshops).
> 
> Italy, Croatia, Slovenia, ... all have a lot of problems.
> 
> What if you divide the work among us - for example - I am from Slovenia, and I can make a complete DB of Slovenian states/cities in a week or so.
> 
> By the way, It would be great if you could add zip codes / postal codes for states/cities.
> States / Cities should be generic and not like "Ljubljana City Municipality" --> "Ljubljana" or "Dravlje District" -> "Dravlje"
