### ISSUE TITLE
Relate States with Timezones

### ISSUE THREAD

**Issue by NadeemAraman** [dr5hn/countries-states-cities-database#453]
### Discussed in https://github.com/dr5hn/countries-states-cities-database/discussions/451

<div type='discussions-op-text'>

<sup>Originally posted by **NadeemAraman** May 27, 2022</sup>
Dear dr5hn , first of all thank you for this wonderful api , second is there anyway that i can bring up or get the time zone of a specific state/city ? i'm saying this because for example russia has more than 8 different timezones and the project i'm working on need to relate each state to its timezone , thanks in advance</div>

**Comment by dr5hn** [comment]
@NadeemAraman Nope, not at the moment.

**Comment by NadeemAraman** [comment]
Okay thanks .
