### ISSUE TITLE
For countries, `phone_code` sometimes include area code and sometimes does not.

### ISSUE THREAD

**Issue by MaybeThisIsRu** [dr5hn/countries-states-cities-database#457]
For example, for the US, the phone code is `1` which is correct if we consider **country codes**.

For the [Dominican Republic](https://www.howtocallabroad.com/dominican-republic/), the phone code in the `countries-states-cities-database` is listed as `1809 and 1829` which is correct if we consider **country+area codes**. Country code being `1` and area codes being `809` and `829` (and also `849`, but that's besides the point right now).

What methodology is being used? Can we rename `phone_code` to correctly reflect if the field means `country_code` or `country_area_code`?

**Comment by dr5hn** [comment]
@MaybeThisIsRu Thanks for reporting. 🎉 

This column is messed up actually, Previously I took data from this resource https://restcountries.com/v2/all

They've updated the calling codes to be more accurate now. So I will soon update them as per the new version. https://restcountries.com/v3.1/all

**Comment by dr5hn** [comment]
Fixed in #835 835
