### ISSUE TITLE
coordinates issues

### ISSUE THREAD

**Issue by deanthinker** [dr5hn/countries-states-cities-database#459]
Hi, Thanks for all the efforts you put into this projects along with great generousity of sharing it with everyone.
I recently found an issue with the accuracy of the coordinates in the states table.
For instance, in states table ID 2258 (Hunan) the coordinates it points to a resturant named 'Hunan ... resturant' in the US. I think there must be some other coordinates issue similar to this.

Thanks again for your generousity.

**Comment by dr5hn** [comment]
@deanthinker Thanks for reporting. Will fix them soon.

**Comment by dr5hn** [comment]
@deanthinker Thanks for reporting. This has been fixed now.

Let me know if you find any other states with the same issue.
