### ISSUE TITLE
SQL File Encoding Incorrect

### ISSUE THREAD

**Issue by andreobrown** [dr5hn/countries-states-cities-database#46]
The SQL database dumps are not correctly encoded. Therefore, special characters are not exported properly. This results in the data files containing strings like these:

`AÄ«bak`
`MontrÃ©al`
`ColÃ³n Department`

Based on the meta data in the SQL files, it seems that you are using `utf8mb4` as your DB encoding. To export the data in the correct format, specify the encoding when exporting the data, as shown here:

`mysqldump -u user_name -p database_name --default-character-set=utf8mb4 --result-file=date_file_name.sql`

If you re-export the SQL files, I will test them for you.

**Comment by andreobrown** [comment]
Any chance that we can get a new dump? Here is a sample of the data when imported in to MySQL using MySQL Workbench:

![Screenshot 2020-04-01 at 23 46 57](https://user-images.githubusercontent.com/1885207/78208748-27710200-7473-11ea-93d1-03b417db6f48.png)

**Comment by dr5hn** [comment]
@andreobrown Thanks for reporting.

Will get it fixed by this weekend.

**Comment by dr5hn** [comment]
@andreobrown @jacobszpz
Finally Fixed with #57. 🎉
