### ISSUE TITLE
[QUESTION] are provinces supported by this db ?

### ISSUE THREAD

**Issue by fasenderos** [dr5hn/countries-states-cities-database#461]
Hi, first of all thanks for this great resource. 

Are the provinces supported by this db? It seems to be true from the description of this repo "World countries, states, regions, **provinces**, cities, towns ... ", but not from the demo.

E.g. `Avigliana` is in province of `Torino` and I'm expected this information in something like `"province_name": "Torino"`, or I'm missing something?

![image](https://user-images.githubusercontent.com/1219087/176152544-480c9fca-5510-41d0-9f38-f4f74a40a955.png)

Thanks in advance

**Comment by dr5hn** [comment]
@fasenderos Nope, not yet. Only 3 level structure is being followed. I believe the `province` level which you're expecting is within 3rd level only (i.e. Cities)

**Comment by dr5hn** [comment]
@fasenderos I was wrong. Provinces are specified within States table.

It's messed up actually, region and provinces are on the same level. I need to actually get rid of regions completely from states table and distribute the cities of those region among provinces.

Requires lots of manual work. Arghh..

Have you got any JSON or SQL source of data for Italy which has cities attached to provinces?

**Comment by dr5hn** [comment]
@fasenderos I think i found one. https://raw.githubusercontent.com/lfbellante/package-laravel-italy/main/database/storage/comuni.json 

Can you please let me know if this is correct source of information?

**Comment by dr5hn** [comment]
Please follow #535
