### ISSUE TITLE
N'Djamena missing as a city?

### ISSUE THREAD

**Issue by Michaud2** [dr5hn/countries-states-cities-database#469]
Hi,

I'm new to Github and also to your project, so I don't know if it was worth an "issue" statement, but I think N'Djamena (Chad's capital) is not considered a city in the files. It is clearly identified as the capital of Chad and also as a state in the countries+states+cities file, but it doesn't show up at all in the cities file (neither by using the Wikidata object code Q3659 for search).

Even if it's a region with a special status, I think it should also show up as a city in the cities file and also under the state named "N'Djamena" instead of just "cities": [], just like it does for other regions with special statuses like Berlin or Beijing.

And also, thank you so much for this project! Open and complete resources concerning cities are somewhat rare on the internet, much to the dismay of political students/scientists like myself...

**Comment by dr5hn** [comment]
@Michaud2 Thanks for reporting. Have added N'Djamena as a city.
