### ISSUE TITLE
Bangladesh Cities missing

### ISSUE THREAD

**Issue by ravichaurasia2021** [dr5hn/countries-states-cities-database#475]
Hello

When I selected the country Bangladesh in the right side showed a State list but when I select some State but City list show me not found the city. so please update database because some customer-facing this issues

**Comment by dr5hn** [comment]
Country: Bangladesh
States (equivalent): Divisions
Bangladesh is divided into 8 administrative divisions, which are the closest equivalent to states:

Barishal
Chattogram (formerly Chittagong)
Dhaka
Khulna
Mymensingh
Rajshahi
Rangpur
Sylhet


Counties/Districts (equivalent): Districts
Each division is further divided into districts. There are 64 districts in total.
Cities and Towns:

City Corporations: These are the largest cities, governed by elected mayors. Examples include Dhaka, Chattogram, Khulna, and Rajshahi.
Pourashavas (Municipalities): Smaller towns and cities.
Rural areas are further divided into Upazilas (sub-districts) and Union Parishads.
