### ISSUE TITLE
A whole region of Finland is missing with the third largest city in the country: Tampere

### ISSUE THREAD

**Issue by japajala** [dr5hn/countries-states-cities-database#478]
A whole region of Finland is missing, see map screenshot attached. This would be in the Pirkanmaa province with the third largest city in the country: Tampere, and the city of Nokia famous from the late cell phone company Nokia. I would not find any of the smaller cities in the region either.

![Screen Shot 2022-08-23 at 8 15 11 AM](https://user-images.githubusercontent.com/70453169/186168041-cc6e8fe8-3452-4872-b8c1-b4bf507d2b57.png)

**Comment by japajala** [comment]
Wikidata: https://www.wikidata.org/wiki/Q40840

**Comment by dr5hn** [comment]
@japajala Thanks for reporting. Have updated the all cities of the whole "Pirkanmaa" region.
