### ISSUE TITLE
Translation for States and Cities

### ISSUE THREAD

**Issue by miaosun** [dr5hn/countries-states-cities-database#479]
Hi, I noticed that we have "translations" entry for Countries names, however we don't have that for States and Cities. 
Will the translations be added in the future? Is there any easy way each one of us can help to make that happen by adding corresponding translations of the States and Cities in our native languages?

![201661339510_ pic](https://user-images.githubusercontent.com/7039941/186408104-4d6f4ce4-e81e-47fc-9b98-9cdce698beef.jpg)

**Comment by dr5hn** [comment]
@miaosun Thanks for the suggestion. Will try to add them. No ETA Please.

**Comment by joaorb64** [comment]
This is highly related to https://github.com/dr5hn/countries-states-cities-database/issues/466. Maybe by default everything should be in English (i.e. "Lisbon") but have a translation key ("pt": "Lisboa"). Same for the so common federal districts, etc.
