### ISSUE TITLE
How to use "country-state-city" module in typescript

### ISSUE THREAD

**Issue by mr-new-0509** [dr5hn/countries-states-cities-database#485]
Hello, there.
Am faced a problem. Can't use "country-state-city" module in typescript?
I tried this command to use it but faced this error.
![image](https://user-images.githubusercontent.com/86947718/187138079-2ac8d630-3f78-470a-ad2c-33a79ec4f7bb.png)

Could you let me know the solution?
Thank you.

**Comment by dr5hn** [comment]
@mr-new-0509 Wrong repo for the issue, I am not the owner of this NPM package.

You should be posting this to https://github.com/harpreetkhalsagtbit/country-state-city
