### ISSUE TITLE
issue with Ts declaration of the country-state-city module

### ISSUE THREAD

**Issue by abhi-bigstep** [dr5hn/countries-states-cities-database#487]
![Screenshot (97)](https://user-images.githubusercontent.com/98146057/187183237-a900ba65-5e13-46d1-82a5-c3d4ac6252fc.png)
please resolve it just by declaring the type of module, till then we can use require for importing its functionalities.

**Comment by dr5hn** [comment]
@abhi-bigstep Wrong repo for the issue, I am not the owner of this NPM package.

You should be posting this to [harpreetkhalsagtbit/country-state-city](https://github.com/harpreetkhalsagtbit/country-state-city)
