### ISSUE TITLE
Missing city in country MX state COL

### ISSUE THREAD

**Issue by balbuena** [dr5hn/countries-states-cities-database#491]
{
  "id":,
  "name": "Manzanillo",
  "state_id": 3472,
  "state_code": "COL",
  "state_name": "Colima",
  "country_id": 142,
  "country_code": "MX",
  "country_name": "Mexico",
  "latitude": "19.2719444°",
  "longitude": "-104.31583055",
  "wikiDataId": "Q739908"
}

**Comment by dr5hn** [comment]
@balbuena Ok will add it soon.
