### ISSUE TITLE
Any way to select city details by city id vs country code + state code?

### ISSUE THREAD

**Issue by pearcircuitmike** [dr5hn/countries-states-cities-database#496]
I want to get the country that each city is in from the "list all cities" functionality. What's the best way to do this? Due to some ssr limitations, I need to determine which country each city is in by the id passing the country and state codes into each city's page and then fetching the city details from that. Thanks!

**Comment by pearcircuitmike** [comment]
I should add I'm working via the API

**Comment by sergio-ob** [comment]
Hey! Any update on this? I don't know how to get city details :(

**Comment by dr5hn** [comment]
@pearcircuitmike //cc @sergio-ob 
This API Route is still on my TO-DO list. No ETA Please.
