### ISSUE TITLE
Support for Microsoft SQL Server?

### ISSUE THREAD

**Issue by JamoCA** [dr5hn/countries-states-cities-database#501]
Are there any plans to generate SQL files to support importing the data into Microsoft SQL Server?

I compared the SQL data with the CSV file and would prefer to use the SQL files since they contain more complete data.

If not, is there a MSSQL schema that can be provided so that tables with the best datatypes + length can be created prior to bulk importing the CSV data? (The column names for SQL and CSV aren't the same.)

Thanks!

**Comment by SilverBull** [comment]
You just have to convert it with the correct syntax / type and collation you want.
```sql
CREATE TABLE test.dbo.countries (
	id int IDENTITY(0, 1) NOT NULL,
	name varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	iso3 char(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	numeric_code char(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	iso2 char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	phonecode varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	capital varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	currency varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	currency_name varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	currency_symbol varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	tld varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	native varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	region varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	subregion varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	timezones varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	translations varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	latitude decimal(10, 8) DEFAULT NULL,
	longitude decimal(11, 8) DEFAULT NULL,
	emoji varchar(191) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	emojiU varchar(191) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	created_at datetime DEFAULT getdate() NULL,
	updated_at datetime DEFAULT getdate() NOT NULL,
	flag tinyint DEFAULT 1 NOT NULL,
	wikiDataId varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL DEFAULT NULL,
	CONSTRAINT countries_PK PRIMARY KEY (id)
);
```

**Comment by JamoCA** [comment]
Thanks. It's primarily the same for table creation, but the rest of the SQL (after table creation) that performs the inserting doesn't work with MSSQL.

If these instructions were intended to be used with the CSV file, the CSV file doesn't contain `translations`, `flag` or `wikiDataId` columns and would be `NULL`. I guess I could consume the JSON file with an application and manually update the countries with the 3 missing columns.  It's not the most performant, but is it the only options for MSSQL users?  (Thanks.)

**Comment by SilverBull** [comment]
Well I eventually created the tables on a mysql and then copied the data to the mssql db after creating the tables by converting the create statement. I guess in the end it just comes down to the most practical method for everyone
