### ISSUE TITLE
Fetch details from OpenStreetMaps

### ISSUE THREAD

**Issue by joaorb64** [dr5hn/countries-states-cities-database#506]
Hi, this is only a suggestion. I recently found out about this API and thought it could be used to help with some kind of automation, especially for latlng and translations: https://nominatim.openstreetmap.org/ui/search.html
Would this be useful? What kind of information could/should be fetched from it?

**Comment by dr5hn** [comment]
@joaorb64 Thanks for the suggestion. However, I've reviewed the URL but unfortunately is of no use.
