### ISSUE TITLE
duplicate cities for Saudi arabia

### ISSUE THREAD

**Issue by thenaazimkhan** [dr5hn/countries-states-cities-database#507]
when calling City.getCountryByCode(countryCode) // countryCode = 'SA'
this is given duplicate cities for Saudi Arabia.

![WhatsApp Image 2022-09-28 at 6 03 40 PM](https://user-images.githubusercontent.com/95960950/192799875-b2b9235a-df7a-4347-8bd1-577e793e2187.jpeg)

**Comment by dr5hn** [comment]
Hi @thenaazimkhan,

Thanks for reporting. 👍🏼 I will fix it ASAP.

**Comment by manojkumartts** [comment]
> 

@dr5hn Any update on this?

**Comment by dr5hn** [comment]
@thenaazimkhan I have fixed the duplicate cities in this database, but I think you are using the npm package, I will raise a PR with a fix of data there and will let you know.

**Comment by thenaazimkhan** [comment]
thanks, darshan

Yes, I am using it via npm.


*Thanks & Regard*
*Naazim Khan*
*Software Engineer*
+971 50 381 2267
