### ISSUE TITLE
Empty response for Iraq (cities&states)

### ISSUE THREAD

**Issue by it-AhmedTaha** [dr5hn/countries-states-cities-database#523]
Request to 
https://api.countrystatecity.in/v1/countries/IQ/cities
or
https://api.countrystatecity.in/v1/countries/iq/cities

return 200 status code and empty response {}

**Comment by dr5hn** [comment]
@it-AhmedTaha This should have been fixed now. Can you please verify?

**Comment by it-AhmedTaha** [comment]
Yes, it is working fine now. Thank you.
