### ISSUE TITLE
API is no longer returning state and country data

### ISSUE THREAD

**Issue by pearcircuitmike** [dr5hn/countries-states-cities-database#525]
I no longer receive state or country data from the API - worked yesterday but not today. No changes, just redeployed the same code and now receive no data.

**Comment by pearcircuitmike** [comment]
Status page says everything is fine, so a bit confused.

**Comment by dr5hn** [comment]
@pearcircuitmike Thanks for letting me know. Checking...

**Comment by dr5hn** [comment]
@pearcircuitmike Can you please check now?

**Comment by pearcircuitmike** [comment]
good now thanks

**Comment by pearcircuitmike** [comment]
Was fine yesterday but seems to be very slow today - my latest build timed out (prior was 25 mins, this one timed out at 45 max)

**Comment by dr5hn** [comment]
@pearcircuitmike Should be fast now. I've fixed the issue.
