### ISSUE TITLE
State CN NM returns invalid JSON

### ISSUE THREAD

**Issue by pearcircuitmike** [dr5hn/countries-states-cities-database#526]
![Screen Shot 2022-10-14 at 9 51 37 AM](https://user-images.githubusercontent.com/19859579/195863728-ae5c93f7-aa9a-412f-86e5-e4f715b0c3d2.png)

Looks like the API now returns invalid JSON for China, Inner Mongolia (NM province/state code)

**Comment by pearcircuitmike** [comment]
I haven't found this issue on any other state yet

**Comment by dr5hn** [comment]
@pearcircuitmike What are you trying to achieve?

Are you trying to fetch cities or state details?

Can you show me the API Url with params you're passing?

**Comment by pearcircuitmike** [comment]
I'm trying to replicate but builds are timing out again -  I think the API has slowed down similar to last week

**Comment by dr5hn** [comment]
@pearcircuitmike What do you mean by builds? Are you trying to run bulk API calls at a time?

If yes, how many?

**Comment by dr5hn** [comment]
@pearcircuitmike In this case, I would say you should use a direct JSON file hosted on GitHub.

https://cdn.jsdelivr.net/gh/dr5hn/countries-states-cities-database/countries%2Bstates.json
