### ISSUE TITLE
Mauritius updated states/cities

### ISSUE THREAD

**Issue by geerishw** [dr5hn/countries-states-cities-database#529]
Hello attached latest update for Mauritius.
States = District in Mauritius
Cities = Main Cities/Towns in Mauritius.

Beau Bassin - Rose Hill(BR) is not a state
Curepipe(CU) is not a state
Port Louis(PU) is not a state 
Quatre Bornes (QB) is not a state
Vacoas Phoenix (VP) is not a state
[GeoLocation_table_Mauritius.xlsx](https://github.com/dr5hn/countries-states-cities-database/files/9854436/GeoLocation_table_Mauritius.xlsx)

See attached for updated States/Cities names.

**Comment by dr5hn** [comment]
@geerishw Thanks for reporting and sharing the updated city data. I will try to update them soon.

**Comment by geerishw** [comment]
Thanks @dr5hn

**Comment by geerishw** [comment]
@dr5hn when will be fixed ? when is the next update ?

**Comment by geerishw** [comment]
[GeoLocation_table_Mauritius with lat_long.xlsx](https://github.com/dr5hn/countries-states-cities-database/files/10344390/GeoLocation_table_Mauritius.with.lat_long.xlsx)

Updated the excel file as per your format and added the latitude and longitude information

**Comment by dr5hn** [comment]
@dr5hn The next update is within this month on some weekend, i will try to get these updated within this month. Thanks for the nudge!

**Comment by geerishw** [comment]
> @geerishw The next update is within this month on some weekend, i will try to get these updated within this month. Thanks for the nudge!

Hey Darshan @dr5hn - when update  planned ?

**Comment by geerishw** [comment]
Hey Darshan @dr5hn - will there be an update this month ?

**Comment by geerishw** [comment]
@dr5hn - we have few lines which are duplicated which have to be deleted and also some new cities added.

[Duplicates to delete.xlsx](https://github.com/dr5hn/countries-states-cities-database/files/11076810/Duplicates.to.delete.xlsx)

[Cities to add.xlsx](https://github.com/dr5hn/countries-states-cities-database/files/11076811/Cities.to.add.xlsx)

**Comment by dr5hn** [comment]
Fixed in #846
