### ISSUE TITLE
Missing Region and Sub-Region

### ISSUE THREAD

**Issue by AyYildizPilot** [dr5hn/countries-states-cities-database#556]
Hello,
Countries in row 30 and 96 "Bouvet Island" and "Heard Island and McDonald Islands" Row 96 region appears as "Australia and New Zealand" in some sources.
Line 30 Bouvet Island region of South America in some sources. Why are these rows blank in your tables?

When the countries combine the similar ones in the region column in the table, 6 regions remain;
Is the region named Polar wrong? Shouldn't it be from Australia?

**Comment by dr5hn** [comment]
Hi @AyYildizPilot,

Antarctica, Bouvet Island, and Heard Island and McDonald Islands do not fall under any specific region in terms of administrative divisions. Antarctica is a continent without any official countries or regions, and it is governed by the Antarctic Treaty System. Bouvet Island is an uninhabited territory of Norway, and Heard Island and McDonald Islands are uninhabited territories of Australia. These remote locations are not typically categorized under specific regions in the same way as inhabited areas.

Hence Bouvet Island, and Heard Island and McDonald Islands are not assigned with any regions.

"Polar" region is a commonly used term to refer to regions near the Earth's polar areas, which may include territories such as Antarctica and other polar regions

Hope that makes sense.
