### ISSUE TITLE
How to get all country properties in a single API call

### ISSUE THREAD

**Issue by Rohan-Rajesh** [dr5hn/countries-states-cities-database#563]
Hi,

I'm currently building an app which requires a login with mobile number supporting international customers, I looked thorough the API and really liked it, now I'm wondering how to get all properties of all countries in a single API call instead of first getting all countries and then getting the country details, making an api call for each and every country would not be very efficient so in short I need a way to get the country name, code, id, phonecode and emoji with one single API call

Any help would be appreciated
Thanks

**Comment by w01ki3** [comment]
You can access the documentation and necessary documents from the link below.
https://countrystatecity.in/
and again you can request api key from this link
https://forms.gle/ckZ8Gub6jS9sUihJA

**Comment by Rohan-Rajesh** [comment]
The problem I'm trying to highlight in this issue isn't available in the docs

**Comment by dr5hn** [comment]
Hi rohan,

At the moment you can't fetch all details in single api call.. you may use countries.json from github to do this.
