### ISSUE TITLE
Postgres Database... Maybe?

### ISSUE THREAD

**Issue by dpkg-i-foo-deb** [dr5hn/countries-states-cities-database#564]
Hello, I plan to use and adapt the database provided in this repository for one of my projects. However, no Postgres version exists. I took the countries+states+cities.json file on the root of the repository and used GORM to create the models. The only difference is I separated the country translations to another table

I forked the repository and added the [script](https://github.com/dpkg-i-foo-deb/countries-states-cities-database/blob/master/sql/world_postgres.sql) to it... Maybe it will be useful for anybody?

![world - public](https://user-images.githubusercontent.com/80849765/212166609-20362423-b2a6-4f0f-90b9-cdc3438c06cd.png)

**Comment by dr5hn** [comment]
Postgre is now added! Yay! 🎉
