### ISSUE TITLE
Missing Minnesota cities

### ISSUE THREAD

**Issue by jschaeppi** [dr5hn/countries-states-cities-database#571]
There are missing cities in state of minnesota in the United States especially the Major cities such as Saint Paul and Minneapolis.

**Comment by Sourjaya** [comment]
###143 Missing entries.
I looked up wikipedia and apparently there are 143 missing cities from the state of Minnesota.

-  **Can I take up this issue and add those entries**.
-  **I would like to be assigned with this issue**.

**Comment by jschaeppi** [comment]
> ### 143 Missing entries.
> I looked up wikipedia and apparently there are 143 missing cities from the state of Minnesota.
> 
> * **Can I take up this issue and add those entries**.
> * **I would like to be assigned with this issue**.

Go ahead.

**Comment by dr5hn** [comment]
@Sourjaya Thanks for stepping forward to fix this issue. Really appreciate it

Please read CONTRIBUTION GUIDELINES first and then start worj

**Comment by Sourjaya** [comment]
@dr5hn I will start be starting next weel if that's okay. Thank You.

**Comment by dr5hn** [comment]
@Sourjaya No problem!

**Comment by dr5hn** [comment]
@jschaeppi Major cities mentioned by you are already available in the Database.

Major cities included in this DB's are as follows:
Minneapolis
Saint Paul
Rochester
Duluth
Bloomington
Brooklyn Park
Plymouth
Saint Cloud
Woodbury
Eagan
Maple Grove
Coon Rapids
Eden Prairie
Burnsville
Blaine
Lakeville
Minnetonka
Apple Valley
Edina
St. Louis Park
