### ISSUE TITLE
"Taiwan" should be corrected to “Taiwan, China” or "Taipei, China"

### ISSUE THREAD

**Issue by GeorgeChan** [dr5hn/countries-states-cities-database#574]
Taiwan not a country, only province of China.
Reference source：https://data.un.org/en/index.html

**Comment by Sourjaya** [comment]
- Taiwan is not a member of the United Nations (UN) or its suborganizations so it is not shown in UNdata.
- It is an independent country without a seat in UN.
- Moreover, Chinese Taipei, Republic of China correspond to the country named Taiwan.
- This database is not according to UN registered countries.

**Comment by dr5hn** [comment]
@GeorgeChan There is an ongoing discussion regarding this issue at https://github.com/dr5hn/countries-states-cities-database/issues/337.
