### ISSUE TITLE
Readme next update date is not updated as of March 1st, 2023 -- Current value: 3rd December 2022

### ISSUE THREAD

**Issue by jeffward01** [dr5hn/countries-states-cities-database#576]
Readme next update date is not updated as of March 1st, 2023 -- Current value: 3rd December 2022

![image](https://user-images.githubusercontent.com/12589359/222324334-cd061ff2-cb06-4646-827c-2a34e612a1b5.png)

**Comment by Divuzki** [comment]
How is this an issue?

**Comment by Divuzki** [comment]
How is this an issue?

**Comment by dr5hn** [comment]
@jeffward01 Fixed.
