### ISSUE TITLE
'United States minor outlying islands' states are missing 

### ISSUE THREAD

**Issue by harshal05** [dr5hn/countries-states-cities-database#580]
**United States minor outlying islands** pl (plural only) A collection of islands and archipelagos, consisting of various dependent territories of the United States, including: Baker Island, Howland Island, Jarvis Island, Johnston Atoll, Kingman Reef, the Midway Islands, Navassa Island, Palmyra Atoll, and Wake Island but currently this islands are getting listed under **United States** as states.
Ideally this above islands should be listed under **United States minor outlying islands** as states.

Wiki link for reference:

https://en.wikipedia.org/wiki/United_States_Minor_Outlying_Islands#:~:text=The%20minor%20outlying%20islands%20and,Caribbean%20Sea%20(Navassa%20Island).

**Comment by dr5hn** [comment]
@harshal05 Nice idea. Have added them.
