### ISSUE TITLE
Remove duplicate cities in India

### ISSUE THREAD

**Issue by TejaGB** [dr5hn/countries-states-cities-database#581]
Please remove the following duplicate cities from India list:
BR	Madhipura
CT	Raj-Nandgaon
DH	Daman District
GJ	Kawant
GJ	Paliyad (Bhavnagar)
GJ	Vinchia
HR	Faridabad District
HR	Fatehabad District
HR	Rewari District
JK	Bandipura
JK	Gandarbal
KA	Ballary
KL	Thrissur District
MH	Ahiri
MH	Ahmadnagar
MH	Akkalkot
MH	Amravati Division
MH	Basmath
MH	Bhusawal
MH	Borivli
MH	Buldhana
MH	Gondiya
MH	Kamthi
MH	Khede
MH	Manwath
MH	Sangole
MH	Sasvad
MP	Khandwa district
MP	Umaria District
MZ	Kolasib district
OR	Jagatsinghpur
OR	Kendraparha
OR	Malakanagiri
TG	Jangoan
UP	Gonda (Aligarh)
UP	Gonda City
UP	Mauranwan
WB	Mohanpur community development block

And change the spellings of the following cities:
BR	Mohiuddinnagar	Mohiuddi nagar
CT	Koriya	                Koria
KA	GundlupÄ“t	        Gundlupet
KL	ChÄ“lakara	        Chelakara
KL	MahÄ“	                Mahe
KL	ManjÄ“shvar	        Manjeshvar
KL	NilÄ“shwar	        Nileshwar
KL	PappinisshÄ“ri	        Pappinissheri
KL	ShÅranur	        Sharanur
MH	Ajra	                        Ajara
MH	Ambarnath	        Ambernath
MH	Bhum	                Bhoom
MH	Bid	                        Beed
MP	Bag	                        Bagh
MP	Bakshwaho	        Bakshwaha
TG	Kukatpalli	        Kukatpally

**Comment by Shiva-15072003** [comment]
I need to work on this project
im interested

**Comment by dr5hn** [comment]
@Shiva-15072003 Thanks for showing interest in working on this project. You can get started by picking any [issue](https://github.com/dr5hn/countries-states-cities-database/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) and following the [Contribution Guidelines](https://github.com/dr5hn/countries-states-cities-database/blob/master/.github/CONTRIBUTING.md).

**Comment by TejaGB** [comment]
@dr5hn @Shiva-15072003, The issue is not fixed. No changes are made. Can I know why we closed the issue without actually fixing it? Can't it be fixed?

**Comment by dr5hn** [comment]
@TejaGB I've fixed this issue in DB. The API DB is yet to be updated.
![Screenshot 2023-03-27 at 1 50 13 PM](https://user-images.githubusercontent.com/6929121/227883344-7e8dfe5a-66cb-473c-bd69-a01b5b59c0a0.png)

**Comment by dr5hn** [comment]
@TejaGB I've updated the API Database.
