### ISSUE TITLE
France Countries => states does not  have the cities information

### ISSUE THREAD

**Issue by thenaveensaggam** [dr5hn/countries-states-cities-database#584]
Hi team,

France and United Kingdom Countries , states does not have the cities information.

Can you please add them.

Thank you.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/25869485/224998258-31c0b330-2da5-4d32-9a11-19a5aabd1aef.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/25869485/224998456-a40abf4e-a3b5-4312-b954-ff7ebd3256ea.png">

**Comment by luisTalenta** [comment]
The same happens with Morocco

**Comment by luisTalenta** [comment]
If you need information about the cities of the states of France, you can use this: https://www.france-voyage.com/francia-ciudades/ain-departement.htm#listing

**Comment by dr5hn** [comment]
Duplicate of https://github.com/dr5hn/countries-states-cities-database/issues/473
