### ISSUE TITLE
Why Antarctica is mentioned as a country?

### ISSUE THREAD

**Issue by amitshree** [dr5hn/countries-states-cities-database#588]
It seems Antarctica is a continent and not a country. What is the reason behind mention Antarctica as a country without any capital in the countries.json file?

Also, can continent name will also be added in the countries.json file? region and continent doesn't seem to be same for all countries.

**Comment by dr5hn** [comment]
Hello, thank you for bringing this issue to my attention. While the countries and continents are currently kept together in the countries.json file, I am planning to separate them and create a new continents.json file in the near future.

**Comment by amitshree** [comment]
@dr5hn I believe in country api only countries should be present.

I see "Jamaica" and "Norfolk Island" are mentioned as country and both of them has same capital name "Kingston" which is causing some issue in my app.
