### ISSUE TITLE
How to help improve this database ?

### ISSUE THREAD

**Issue by hydrocat** [dr5hn/countries-states-cities-database#592]
I'd like to add a couple missing translations but I didn't find a guide in the README.md

**Comment by w01ki3** [comment]
> I'd like to add a couple missing translations but I didn't find a guide in the README.md

You just need to make all the changes in the sql/world.sql file. For translation, you must make changes in the translations column in the countries table.

**Comment by dr5hn** [comment]
To help improve the project, you can follow these general steps:

**Fork the Repository:** Start by forking the project's repository to your own GitHub account. This will create a copy of the project that you can freely modify.

**Clone the Repository:** Clone the forked repository to your local development environment using Git. This will allow you to make changes to the project's files.

**Make Your Changes:** Make the necessary modifications referring [CONTRIBUTING.md](https://github.com/dr5hn/countries-states-cities-database/blob/master/.github/CONTRIBUTING.md)

**Commit and Push:** Once you are satisfied with your changes, commit them to your local repository and push them to your forked repository on GitHub.

**Submit a Pull Request:** Open a pull request from your forked repository to the original project's repository. Provide a clear and concise description of the changes you made and why they are beneficial. The project maintainers will review your pull request and provide feedback or merge it into the main project if it meets their criteria.

Remember to follow the guidelines specified in the project's [CONTRIBUTING.md](https://github.com/dr5hn/countries-states-cities-database/blob/master/.github/CONTRIBUTING.md) file for the specific requirements and processes associated with contributing to the project.
