### ISSUE TITLE
using country-state-city": "^3.1.2 Not returning United States City's

### ISSUE THREAD

**Issue by AlgoHussle** [dr5hn/countries-states-cities-database#597]
This package is not returning US cities in my nextjs 13.3 project

**Comment by dr5hn** [comment]
If you encounter any issues related to the NPM package, you can raise them on the GitHub repository for the package. Here is the link to the repository where you can submit your issues: [GitHub Repository - country-state-city](https://github.com/harpreetkhalsagtbit/country-state-city#readme)

Simply navigate to the repository and click on the "Issues" tab to create a new issue. Provide a detailed description of the problem you're facing, including any relevant code snippets or error messages. The package maintainer will review your issue and provide assistance to resolve it.

Let me know if there's anything else I can assist you with!
