### ISSUE TITLE
Remove the "+" symbol from all instances of country "phone_code" to keep the database uniform

### ISSUE THREAD

**Issue by BenJackGill** [dr5hn/countries-states-cities-database#599]
There currently 26 countries that have a `+` symbol in their `phone_code` property. For example `Aland Islands` has `"phone_code": "+358-18"`.

I assume that is a mistake because all the other 224 countries do not include the `+` symbol in their `phone_code` property. For example `Afghanistan` has `"phone_code": "93"`.

This causes problems when using the `phone_code` field because we add our own `+` symbol to the start of country dial codes, and now those 26 countries mentioned above have `++` by mistake.

To keep the database uniform I suggest `phone_code` should never include the `+` symbol and it should be removed from the 26 countries that already have it included.

**Comment by dr5hn** [comment]
@BenJackGill Thanks for reporting.

I believe those with suffixes have `+` symbol. I will make it uniform soon.

**Comment by RohitYadav07** [comment]
![image](https://github.com/dr5hn/countries-states-cities-database/assets/99853067/66580633-454b-4f12-aa3e-4eaf839ec246)
Removed the "+" symbol from all instances of country "phone_code" to keep the database uniform.

**Comment by BenJackGill** [comment]
Judging by the last comment from @RohitYadav07 it looks like he did an update to fix this problem last year. But checking the database right now I can see there are still 26 countries with a `+` symbol in the `phone_code` field.
