### ISSUE TITLE
 Istanbul is Missing from List of Cities in Turkey

### ISSUE THREAD

**Issue by kbingol** [dr5hn/countries-states-cities-database#601]
Hello,

I was trying to list all cities in Turkey using the City.getCitiesOfCountry("TR") function, but I noticed that Istanbul is missing from the list. Istanbul is the largest city in Turkey and a major cultural and economic hub, so it's surprising to see it omitted from the list.

Can someone please investigate why Istanbul is missing from the list and update the database accordingly? It's important to have accurate and comprehensive data for developers and users who rely on this database.

State Code: 34
Name: İstanbul

Thank you.

![Ekran görüntüsü 2023-05-13 150646](https://github.com/dr5hn/countries-states-cities-database/assets/36646283/3973a4f2-8d3e-4d11-85d1-52f63c36e54f)

**Comment by w01ki3** [comment]
Hello @kbingol
Istanbul is an important city in Turkey.
and id 2170 is also registered in the world.sql file.
However, universal definitions may differ from country to country.
The recognition they call the state is called the city in our country.
The layers in this project are called Countries->States->Cities. (Ülkeler->Şehirler->İlçeler)
You can find all the information and Istanbul (our beautiful city) in the link.
https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/master/sql/world.sql

URL to request:
curl -X GET "https://api.countrystatecity.in/v1/countries/TR/states" -H "accept: application/json" -H "X-CSCAPI-KEY: "******"

thanks

**Comment by kbingol** [comment]
Hi @w01ki3 

Thank you for letting me know about it. I appreciate the clarification and the API link you provided.

Thanks! :)

**Comment by molaeiali** [comment]
Istanbul is still missing from the CSV in master, I don't know why this issue is closed.
https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/master/csv/cities.csv

![image](https://i.ibb.co/tcgz5z2/Screenshot-from-2023-06-25-12-54-11.png)

**Comment by w01ki3** [comment]
Please read what I wrote above.
This is a concept that can vary from country to country.

this is where you should look
https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/master/csv/states.csv
