### ISSUE TITLE
Indonesian new states/provinces

### ISSUE THREAD

**Issue by acothaha** [dr5hn/countries-states-cities-database#602]
Greetings!!
Since 2022, Papua and Papua Barat were divided into 6 provinces

1. Papua
2. Papua Barat
3. Papua Barat Daya
4. Papua Tengah
5. Papua Pegunungan
6. Papua Selatan

You can look it up here: https://en.wikipedia.org/wiki/Provinces_of_Indonesia

Thanks!!

**Comment by dr5hn** [comment]
@acothaha Up to date, hence closing
