### ISSUE TITLE
how can I get zipcode 

### ISSUE THREAD

**Issue by hadi-mansoori** [dr5hn/countries-states-cities-database#609]
I need zipcode of cities ? how can I calculate  It ?

**Comment by dr5hn** [comment]
Unfortunately, the current version of the database does not include zipcodes. It provides information such as countries, states, regions, cities, and other details, but zipcodes are not included. If you require zipcodes, you may need to explore alternative sources or databases specifically focused on zipcodes. Let me know if there's anything else I can assist you with.
