### ISSUE TITLE
Add Timezones to Cities

### ISSUE THREAD

**Issue by seljabali** [dr5hn/countries-states-cities-database#613]
Currently timezones are placed at a country level which is beneficial, however it'd be even more beneficial to have cities include what timezone they're in.

**Comment by dr5hn** [comment]
@seljabali 
Thank you for your input, but please note that this is intended as a suggestion rather than an issue. We kindly request that you utilize the existing discussion topic to share your suggestions.

https://github.com/dr5hn/countries-states-cities-database/discussions/451

**Comment by seljabali** [comment]
Gotcha. My bad. I've added a [comment](https://github.com/dr5hn/countries-states-cities-database/discussions/451#discussioncomment-5980821) @dr5hn. Thanks for the heads up.
