### ISSUE TITLE
Crimea (state_name: Sevastopol) is part of Ukraine

### ISSUE THREAD

**Issue by DmiPita** [dr5hn/countries-states-cities-database#615]
Hello, we found that you put Crimea's cities (state_name: Sevastopol) as a part of russia, but this is wrong. Since 1991, Crimea has been part of Ukraine. Crimea was annexed in 2014 by the russian federation, but this does not mean that it is now part of russia. So please change it.
![Screenshot from 2023-05-25 08-56-07](https://github.com/dr5hn/countries-states-cities-database/assets/101987532/c0fbccaf-6d19-4e5f-a1ee-706ab995905a)

**Comment by mpathy** [comment]
+1 
It is internationally NOT recoignized as part of Russia, to this very day.

You don't have to be afraid to get into any conflicts by looking into those Github Issues - when in doubt, just look up official data. Very easy.

Thats also the only way you get trusted that your repo is at least halfway correct and useable in projects.

And hey, Russians can fork this repository and remove Ukraine, Georgia and what else from the data and enter there fictional data entries in the fork.
