### ISSUE TITLE
[FEATURE] PostgreSQL support for country, city, state data with GoLang.

### ISSUE THREAD

**Issue by caner-cetin** [dr5hn/countries-states-cities-database#624]
Please do not recommend https://sqlizer.io/ as you did in other issues, JSON and other types of files are snowballed into 20-plus megabyte files that no upload and convert service takes the files now.

 Like, cities.json is freaking 50 megabytes now, my Kate crashed three times, JetBrains refused to open it in write mode, I nuked a small JavaScript website, these all happened just to select a small portion for converting to GoLang structs.

Instead, I just put up a quick script with the help of my dude ChatGPT3,14159265358979323846, that you can. I dont know what you want to do with this, I just did it because original SQL files are not compatible with PSQL.

I also made adjustments:

- Longest city name is 85 chars by **Taumatawhakatangihangakoauauotamateaturipukakapiki-maungahoronukupokaiwhenuakitnatahu** why varchar(255)? This is already a humongous amount of data, why waste further space?
- Longest currency name is Ngultrum, which is 8 chars. why varchar(255)? varchar(42) works by the way. Still, huge gain.
- Longest continent/region area is Antarctica, why varchar(255)?

Don't say "Ooooh because someone will declare a country with 86 chars and you are fucked", we would be fucked if someone declares a city/country with 256 chars too. not an excuse.

- Timezones are now a separate table
```sql
CREATE TABLE timezones (
  id              SERIAL PRIMARY KEY,
  zone_name       VARCHAR(255) NOT NULL,
  gmt_offset      INTEGER NOT NULL,
  gmt_offset_name VARCHAR(255) NOT NULL,
  abbreviation    VARCHAR(255) NOT NULL,
  tz_name         VARCHAR(255) NOT NULL
); 

```

Example:

![image](https://github.com/dr5hn/countries-states-cities-database/assets/92731060/aa50919f-5182-4018-a3b9-96f5608b0ea9)

and `INTEGER[]` in the timezone_id (at countries table) is pointing to the ID in timezones. Didnt make an FK, but putting logic together is really easy.

![image](https://github.com/dr5hn/countries-states-cities-database/assets/92731060/c0d212be-9a2b-4b1c-a37c-901b47167f1e)

- Changed country, timezone, and states to the SMALLSERIAL and its references to SMALLINT. There is no possible way we will have more than 32.767 timezone, countries, and states.
- FIPS code is removed from the state table, as JSON didn't have it.
- ISO2 is removed from the state table, as JSON didn't have it.
- WikiDataID is removed from the state table, as JSON didnt have it.
- Flag is removed from the state table, as JSON didnt have it.
- Any non-string type from the state is not recorded, only string-typed types (????) are inserted.
- In country table, translations is now hold as JSONB instead of plain text.

No errors, and you can run it in plain empty database.

Get the latest version of GoLang, run 

```bash
go mod tidy
go run main.go
```

and have fun! 

https://gist.github.com/DAMACANER/db20c431bd6075a49acc4457de0eb6c3

**Comment by DAMACANER** [comment]
By the way I dont have the knowledge for creating SQL for this. Script is all and best I can provide.

**Comment by caner-cetin** [comment]
@fabiopicchi read the code before running, I forgot what I did here lol. https://gist.github.com/caner-cetin/db20c431bd6075a49acc4457de0eb6c3

**Comment by dr5hn** [comment]
@fabiopicchi //cc @caner-cetin  No need for this i am merging this PR https://github.com/dr5hn/countries-states-cities-database/pull/739 which will add support for postgresql.

**Comment by dr5hn** [comment]
Postgre support is now added! Cheers \m/

**Comment by caner-cetin** [comment]
yeehoo
