### ISSUE TITLE
City Bogota is the Capital from Colombia

### ISSUE THREAD

**Issue by fagsoft1** [dr5hn/countries-states-cities-database#63]
Hello!

For Colombia there aren't some important cities.
Bogotá, is the capital of Colombia.
Medellín, is the capital of Antioquia.

**Comment by dr5hn** [comment]
@fagsoft1 Thanks for reporting. 🎉 Will look in to it ASAP.

**Comment by dr5hn** [comment]
@fagsoft1 Sorry for the delayed response. I dug down to cities, found that

- 👍🏼  Medellin does exist in cities at 21074
- 👎🏼 Bogota does not exist in cities - So I added it.
- added a few more cities that were missing.
- Added a Huila State & its Cities which was missing completely.

Done. Please Verify. #102
