### ISSUE TITLE
A small fix for Cities in Argentina

### ISSUE THREAD

**Issue by jcporcel** [dr5hn/countries-states-cities-database#648]
There is a very understandable error in the list of cities of 2 states in the country of "Argentina"

The problems: 
- The state named "Autonomous City of Buenos Aires" has no cities. 
- The state named "Buenos Aires Province" has listed 10 cities which belong to "Autonomous City of Buenos Aires".

The current list of cities for "Buenos Aires Province" are:

- {id: 682, name: 'Balvanera'}
- {id: 683, name: 'Barracas'}
- {id: 687, name: 'Belgrano'}
- {id: 697, name: 'Boedo'}
- {id: 704, name: 'Buenos Aires'}
- {id: 773, name: 'Colegiales'}
- {id: 1380, name: 'Retiro'}
- {id: 1561, name: 'Villa Lugano'}
- {id: 1570, name: 'Villa Ortúzar'}
- {id: 1576, name: 'Villa Santa Rita'}

These "cities" are more like neighborhoods and they belong to the state named "Autonomous City of Buenos Aires" which is a VERY small city-state with an area of about 250 square kilometers. 

The cities (actual cities with tens of thousands of inhabitants) that do belong to the state "Buenos Aires Province" (a normal state with a area of about 307,000 square kilometers) are the following:

- Almirante Brown
- Bahía Blanca
- Caseros
- Ezeiza
- General San Martín
- Junín
- Lanús
- La Plata
- Lomas de Zamora
- Luján
- Mar del Plata
- Merlo
- Morón
- Olivos
- Pergamino
- Quilmes
- San Isidro
- San Justo
- San Nicolás de los Arroyos
- Tandil
- Tigre
- Zárate

(Source of this list: https://www.britannica.com/topic/list-of-cities-and-towns-in-Argentina-2056026)

**Comment by fk00750** [comment]
Hey @dr5hn can you assign me this issue ?

**Comment by LeandroBarone** [comment]
+1 to this bug report, came to say exactly the same.

A little more information: the region "Ciudad Autónoma de Buenos Aires" should NOT include the cities currently listed for the region "Buenos Aires Province" (Balvanera, Barracas, Belgrano, etc.), those are neighborhoods and have no autonomous government. Instead, it should include a single city, also called "Ciudad Autónoma de Buenos Aires".

The region "Buenos Aires Province" should include these cities:

https://es.wikipedia.org/wiki/Anexo:Ciudades_de_la_provincia_de_Buenos_Aires
