### ISSUE TITLE
Regions/Continents and Subregions

### ISSUE THREAD

**Issue by Freelenzer** [dr5hn/countries-states-cities-database#653]
## Motivation

Reference all countries of a Region/Continent is currently not possible. As well as the connection between subregions and regions is missing. Therefore it is necessary to create a Continents and a Subregions Database. Also localisation of those regions is useful

## Risks

This might break the database

**Comment by Freelenzer** [comment]
I added a Draft PR to discuss this feature:

https://github.com/dr5hn/countries-states-cities-database/pull/657

@dr5hn

**Comment by Freelenzer** [comment]
@dr5hn  How do I create the json from the SQL/Database?

**Comment by dr5hn** [comment]
@Freelenzer Answered your question in the PR.
