### ISSUE TITLE
Add Nationality Information as a New Category

### ISSUE THREAD

**Issue by Ojay-dev** [dr5hn/countries-states-cities-database#670]
The "countries-states-cities-database" repository has proven to be a valuable resource, offering data on countries, states, and cities for various applications. However, to make the database even more comprehensive and relevant, I propose the addition of a new category: "Nationality Information."

**Comment by dr5hn** [comment]
@Ojay-dev Nationality is already added.

https://github.com/dr5hn/countries-states-cities-database/blob/master/csv/countries.csv
<img width="424" alt="Screenshot 2023-09-17 at 7 36 28 PM" src="https://github.com/dr5hn/countries-states-cities-database/assets/6929121/e4e98bd3-1cae-4ff8-a6be-4404f2d2bbff">
