### ISSUE TITLE
No UK city

### ISSUE THREAD

**Issue by Salamouna** [dr5hn/countries-states-cities-database#680]
I can't see any city in the UK
only states

**Comment by RezaNorm** [comment]
yeah i'm facing issues with this one

**Comment by Malin88** [comment]
same here :/

**Comment by ClearSeve** [comment]
GBR is the abbreviation of Great Britain, the UK. The more formal GBR is rarely used in UK.

**Comment by coxy17** [comment]
me too

**Comment by dr5hn** [comment]
Duplicate of #168
