### ISSUE TITLE
France's cities not matching its states code

### ISSUE THREAD

**Issue by romain-sen** [dr5hn/countries-states-cities-database#685]
You cannot find the cities of Paris for instance because when you select Paris, you get the state code of '75C' but the cities have the state code 'IDF' for 'Ile-de-France'.

**Comment by romain-sen** [comment]
Seeing the states data here : 
https://github.com/dr5hn/countries-states-cities-database/blob/master/csv/states.csv

The cities match with the states of type : "metropolitan region", but all the other states (state in these region) have no cities matching. 

A quick fix would have been to filter the state to only get the "metropolitan region" ones with their matching cities, but we don't have access to the type in the code...

The complete fix : make the cities match with the region and with the other state.

**Comment by scramatte** [comment]
+1 here

**Comment by dr5hn** [comment]
@dosubot Please help me fix this and raise a PR.
