### ISSUE TITLE
Feature Request: Prisma Schema w/ Seed Files

### ISSUE THREAD

**Issue by savager** [dr5hn/countries-states-cities-database#687]
Would love for this repo to provide a Prisma Schema (with relations) and the corresponding seed data (updated sql imports) so that this data could be used in Prisma projects easily.

**Comment by dr5hn** [comment]
@savager @maurotrigo @My-kal 

Prisma schema and seed files have been added. Kindly review them and consider submitting a pull request if modifications are required. As the enhancement was generated using AI, and given my limited expertise with Prisma, some refinements may be necessary.
