### ISSUE TITLE
Ladakh - India

### ISSUE THREAD

**Issue by thevikasthakur** [dr5hn/countries-states-cities-database#70]
Ladakh a new U.T. was carved out of Jammu & Kashmir state in India. Leh & Kargil are the two cities in Ladakh. Earlier the two cities were in Jammu & Kashmir state

**Comment by dr5hn** [comment]
@thevikasthakur Gotcha. Thanks for Reporting. Much Appreciated. 🎉

**Comment by dr5hn** [comment]
@thevikasthakur Updated. Hence Closing.
