### ISSUE TITLE
cities.csv out of date with states.csv

### ISSUE THREAD

**Issue by scottgigante** [dr5hn/countries-states-cities-database#717]
Modified state codes (e.g. MX-CDMX -> MX-CMX) haven't been updated in cities.csv -- is something wrong with the csv updater? See e.g. https://github.com/dr5hn/countries-states-cities-database/pull/701/files

**Comment by dr5hn** [comment]
@scottgigante Thanks for the heads up! the issue was created from https://github.com/dr5hn/countries-states-cities-database/pull/697 this PR. It's now been resolved.
