### ISSUE TITLE
states.sql file have a error data

### ISSUE THREAD

**Issue by enzochen** [dr5hn/countries-states-cities-database#732]
the date of id 2272   name is "Shaanxi"  current . the correct name should be "Shanxi"

**Comment by dr5hn** [comment]
@dosubot please label this Issue and also create a sizes label for issues similar you did for PRs. and find out how much effort will be required to solve this issue and label it accordinly.

**Comment by Aakash315** [comment]
![image](https://github.com/user-attachments/assets/7ffff195-63ed-4e68-9f90-49b6236eecf6)
