### ISSUE TITLE
Mauritius - duplicate cities

### ISSUE THREAD

**Issue by geerishw** [dr5hn/countries-states-cities-database#740]
[Cities feedback v2.xlsx](https://github.com/dr5hn/countries-states-cities-database/files/13928527/Cities.feedback.v2.xlsx)

Hello @dr5hn 

You will find in the attached document (highlighted in yellow) :
(i) duplicate cities to be removed
(ii) id 153401 to change state_id, state_code, state_name
(iii) 3 cities to be added

**Comment by CSFlorin** [comment]
I found another dupe with Bogotá D.C. in Colombia
