### ISSUE TITLE
city do not change when selected in the dropdown i guess the error is related to values of option the value is same for all options

### ISSUE THREAD

**Issue by sumiran01** [dr5hn/countries-states-cities-database#743]

**Comment by dr5hn** [comment]
@sumiran01 Issue seems to be on your code end. Is it possible for you to share code here? Make sure to mask API Key when sending code.

**Comment by sumiran01** [comment]
const[city, setcity]=useState(shippingInfo.city);

<select required  name="city" value={city} onChange={(e)=>setcity(e.target.value)}>

     <option>City</option>
     {
      City && City.getCitiesOfState  (country,state).map((item)=>(
        <option key={item.stateCode} value={item.stateCode}>{item.name}</option>
      ))
     }
    </select>

**Comment by dr5hn** [comment]
Can you please share a full code on how you're getting statecode and country code? also content of getCitiesOfState?

**Comment by Ranjeet0605** [comment]
this is use to if any essue related to city {City && City.getCitiesOfState(country,state).map((item)=>(
  
    <option key={item.stateCode} value={item.stateCode}>{item.name}</option>
 ))}
