### ISSUE TITLE
The listing of Friedens in Pennsylvania should be Friedensburg.

### ISSUE THREAD

**Issue by fascom-ft2** [dr5hn/countries-states-cities-database#755]

**Comment by dr5hn** [comment]
@dosubot

**Comment by AF-tl** [comment]
@fascom-ft2  According to the Wikidata Object it is Friedens:

https://www.wikidata.org/wiki/Q1131336

Also the englisch Wikipedia page says Friedens:

https://en.wikipedia.org/wiki/Friedens,_Pennsylvania
