### ISSUE TITLE
Buenos Aires Province and Ciudad Autonoma de Buenos Aires

### ISSUE THREAD

**Issue by leonardotallone** [dr5hn/countries-states-cities-database#758]
Ciudad Autónoma de Buenos Aires is EMPTY. It has no neighborhood inside it, and in the Buenos Aires province, there are no displayed cities...just some neighborhood from the Ciudad Autonoma de Buenos Aires. 
Could it be fixed up???
Thanks a lot Leo

**Comment by dr5hn** [comment]
@dosubot
