### ISSUE TITLE
Missing states for Venezuela

### ISSUE THREAD

**Issue by vicventum** [dr5hn/countries-states-cities-database#76]
Hello Friend! 😁

Checking the `countries+states.json` I realized that the following states were missing for Venezuela:

* **Estate:** Apure, **Capital:** San Fernando de Apure
* **Estate:** Falcón, **Capital:** Coro

Also, for the state *Federal Dependencies of Venezuela*, its correct name would be *Distrito Capital*, whose capital is *Caracas*

**Comment by dr5hn** [comment]
@vicventum Thanks for Reporting. Have fixed this issue in #81.
