### ISSUE TITLE
I can see the issue of encoding. Can anyone help me to solve this encoding issue? Check below listed picture.

### ISSUE THREAD

**Issue by viotile** [dr5hn/countries-states-cities-database#77]
![image](https://user-images.githubusercontent.com/8554562/83522398-3c632380-a4fe-11ea-99b0-068346bd6771.png)

**Comment by dr5hn** [comment]
@viotile Sure, can you please tell me exactly which states are you referring to ?

**Comment by viotile** [comment]
Please refer to attachment. I've marked junk character above the name it is valid for some name but not for others.

> @viotile Sure, can you please tell me exactly which states are you referring to ?

![Updated - Query image Annotation 2020-06-07 112238](https://user-images.githubusercontent.com/8554562/83961524-9cb4e500-a8b1-11ea-8c60-25403a7b557f.png)

**Comment by dr5hn** [comment]
@viotile Ok i will validate names and will try to fix it ASAP.

**Comment by dr5hn** [comment]
UPDATE: Fixed India's all cities encoding issues.

**Comment by dr5hn** [comment]
No more encoding complaints from anyone, hence closing.
