### ISSUE TITLE
API key request page broken

### ISSUE THREAD

**Issue by Ladvace** [dr5hn/countries-states-cities-database#771]
I tried to visit `https://countrystatecity.in/request` to request an API key but I just gate `Page not found`

**Comment by dr5hn** [comment]
@Ladvace I've redirected Request api key to Google Forms. Here's the direct link https://docs.google.com/forms/d/e/1FAIpQLSciOf_227-3pKGKJok6TM0QF2PZhSgfQwy-F-bQaBj0OUgMmA/viewform
