### ISSUE TITLE
UNAUTHORIZED

### ISSUE THREAD

**Issue by LOUISZION** [dr5hn/countries-states-cities-database#773]
Hello Good Day
i am trying to fetch out data using the api but it tells me am not authorized 
my code "public async Task PopulateCities(ChangeEventArgs e)
{
    string apiKey = "VGhtY1BOUGNBUmxneFVHMVRIN05tWVUydW56QU5XU2pHVElOZGtOTQ==";
    registerModel.Country = e.Value.ToString();
    country.CountryShortName = Countries.FirstOrDefault(country => country.CountryName == registerModel.Country).CountryShortName;
    using (var httpClient = new HttpClient())
    {
        var request = new HttpRequestMessage
            {
                Method = HttpMethod.Get,
                RequestUri = new Uri($"https://api.countrystatecity.in/v1/countries/{country.CountryShortName}/states")
            };

        request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        request.Headers.Authorization = new AuthenticationHeaderValue("X-CSCAPI-KEY", apiKey);

        var response = await httpClient.SendAsync(request);

        if (response.IsSuccessStatusCode)
        {
            var contentStream = await response.Content.ReadAsStreamAsync();
            using (var jsonDocument = await JsonDocument.ParseAsync(contentStream))
            {
                var statesArray = jsonDocument.RootElement.EnumerateArray()
                    .Select(x => x.GetProperty("country_name").GetString())
                    .ToList();
                States = statesArray;
            }
        }
    }
     "
     please any solution to this?

**Comment by LOUISZION** [comment]
alright thanks what is the issue

**Comment by dr5hn** [comment]
@LOUISZION Never POST your API Keys in Public. You can reach out to me via Email.
