### ISSUE TITLE
Hong Kong not listed as a city

### ISSUE THREAD

**Issue by MarthinusStrydom** [dr5hn/countries-states-cities-database#78]
Hong Kong is a country and also a city.

**Comment by dr5hn** [comment]
@MarthinusStrydom Did you mean to attach Hong Kong as a city within China ?

**Comment by MerlinPong** [comment]
I sugguest Hongkong should recognized as Hongkong SAR (country level), and contains one city as itself according to other region source I found.

**Comment by dr5hn** [comment]
@MerlinPong Thanks for suggestion. I will also validate from my side as well.

**Comment by dr5hn** [comment]
@MarthinusStrydom //cc @fa1com 

Is there any State/Province available with which I can attach "Hongkong" as a City?
