### ISSUE TITLE
Clearing search is not rendering the whole list

### ISSUE THREAD

**Issue by StellarLogic** [dr5hn/countries-states-cities-database#785]
Clearing search is not rendering the whole list

Steps to reproduce 
 1. Search for any country 
 2. Then clear the search bar using the clear button inside search bar
 3. Observe whole list is not visible as search is cleared

![Screenshot 2024-06-11 095335](https://github.com/dr5hn/countries-states-cities-database/assets/66798245/958ce3ec-3f97-4257-b4ea-6755d9a68ee9)

**Comment by dr5hn** [comment]
Fixed in #837
