### ISSUE TITLE
Question regarding contribution

### ISSUE THREAD

**Issue by dorkyboi** [dr5hn/countries-states-cities-database#788]
The guide states we should modify `world.sql` if we wish to add/change things.
I would like to write a script to add more translations, as doing that manually for thousands of records is just not an option.

Question is if it would be okay to:
- import `world.sql` to database
- let the script modify the database
- generate new `world.sql`

The problem is with the last step - generated output will differ from what we have now, depending on the tool doing the generation.
Would that still be okay? I would imagine it will make reviewing changes in PR literally impossible.

Perhaps you could tell me what tool should I use to produce output similar to original structure?

**Comment by dorkyboi** [comment]
I'll give that a try, let's see how it goes

**Comment by dorkyboi** [comment]
Nope, unfortunately the structure generated by `mysqldump` is different.
For example right now there are CREATE TABLE statements first and then INSERTs, but in the generated file it's CREATE table, INSERT values, CREATE anothertable, INSERT valuesforanothertable
I can submit the file as it is but maybe there's another way?

**Comment by dr5hn** [comment]
@dorkyboi That's completely fine! Go ahead and do your contribution. Rest i will handle.

**Comment by dorkyboi** [comment]
Great, thank you ❤️
