### ISSUE TITLE
Why is Arabic translation listed under "fa" 

### ISSUE THREAD

**Issue by gharam37** [dr5hn/countries-states-cities-database#791]
arabic translation is listed under they key "fa" 

![image](https://github.com/dr5hn/countries-states-cities-database/assets/25537073/0f665b83-9249-4884-b620-6694a27dd6bf)

https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/master/countries%2Bcities.json

**Comment by TerminalDZ** [comment]
Arabic translation not found in translation section.
