### ISSUE TITLE
Missing West Bengal State in India

### ISSUE THREAD

**Issue by ashah2012** [dr5hn/countries-states-cities-database#80]
West Bengal state missing from the country India. 
Missing all the cities in West Bengal.

**Comment by dr5hn** [comment]
@ashah2012 Fixed in #81.
<img width="1052" alt="Screenshot 2020-06-14 at 7 33 30 PM" src="https://user-images.githubusercontent.com/6929121/84595522-f733df80-ae75-11ea-97bf-cd79950e2bea.png">
