### ISSUE TITLE
Problemas al obtener las ciudades en algunos estados de Francia

### ISSUE THREAD

**Issue by faRandstad** [dr5hn/countries-states-cities-database#810]
Hola, existe un problema relacionado a obtener las ciudades relacionadas con los estados de Francia.
Por ejemplo:
🇫🇷 France FR => Ain 01 => No Cities Found.

Este problema ocurre con varios estados, por lo gral con aquellos que sus "state_code" son numeros. Aquellos que son String o caracteres, obtiene las ciudades de manera correcta.
![FranciaProblem](https://github.com/user-attachments/assets/05d8e335-9794-47c5-a6b1-535122699354)

**Comment by dr5hn** [comment]
Duplicate of https://github.com/dr5hn/countries-states-cities-database/issues/473
