### ISSUE TITLE
Some cities are missing or miss defined in country "TZ" in state "Dar es salaam"

### ISSUE THREAD

**Issue by Mudathiralawi** [dr5hn/countries-states-cities-database#819]
In json it is defined that in Dar es salaam there is Magomeni and Dar es salaam only but there are more like Kinondoni, Kigamboni etc

**Comment by Mudathiralawi** [comment]
{
    "id": 1490,
    "name": "Dar es Salaam",
    "country_id": 218,
    "country_code": "TZ",
    "country_name": "Tanzania",
    "state_code": "02",
    "type": "Region",
    "latitude": "-6.79235400",
    "longitude": "39.20832840",
    "cities": [
        {
            "name": "Ilala",
            "latitude": "-6.848738",
            "longitude": "39.284713"
        },
        {
            "name": "Kigamboni",
            "latitude": "-6.849455",
            "longitude": "39.317333"
        },
        {
            "name": "Kinondoni",
            "latitude": "-6.784231",
            "longitude": "39.265676"
        },
        {
            "name": "Temeke",
            "latitude": "-6.904184",
            "longitude": "39.235282"
        },
        {
            "name": "Ubungo",
            "latitude": "-6.806005",
            "longitude": "39.246636"
        }
    ]
}

**Comment by Mudathiralawi** [comment]
`{
    "id": 1490,
    "name": "Dar es Salaam",
    "country_id": 218,
    "country_code": "TZ",
    "country_name": "Tanzania",
    "state_code": "02",
    "type": "Region",
    "latitude": "-6.79235400",
    "longitude": "39.20832840",
    "cities": [
        {
            "name": "Ilala",
            "latitude": "-6.848738",
            "longitude": "39.284713"
        },
        {
            "name": "Kigamboni",
            "latitude": "-6.849455",
            "longitude": "39.317333"
        },
        {
            "name": "Kinondoni",
            "latitude": "-6.784231",
            "longitude": "39.265676"
        },
        {
            "name": "Temeke",
            "latitude": "-6.904184",
            "longitude": "39.235282"
        },
        {
            "name": "Ubungo",
            "latitude": "-6.806005",
            "longitude": "39.246636"
        }
    ]
}
`

**Comment by dr5hn** [comment]
Fixed in #828
