### ISSUE TITLE
Missing Guarda District in Portugal

### ISSUE THREAD

**Issue by sergio-bm** [dr5hn/countries-states-cities-database#82]
Hi!

Guarda District is not in the state table

https://en.wikipedia.org/wiki/Portugal#Administrative_divisions

https://www.wikidata.org/wiki/Q273533

Thanks for your great work!

**Comment by dr5hn** [comment]
@sergio-bm Thanks for Reporting 🎉 . Will take a look.

**Comment by dr5hn** [comment]
@sergio-bm Fixed in #85.
