### ISSUE TITLE
Data not matching with API Demo

### ISSUE THREAD

**Issue by VectorChi** [dr5hn/countries-states-cities-database#820]
Are we still on `'https://api.countrystatecity.in/v1/countries'`?

I am getting incomplete cities for Lagos and I can see more on the demo page.

**Comment by VectorChi** [comment]
@dosu What is the current number of cities on the API endpoint for Lagos, Nigeria?

**Comment by VectorChi** [comment]
@dosubot Which is the current API endpoint?

**Comment by dr5hn** [comment]
@VectorChi API DB is now synced with latest updates.
