### ISSUE TITLE
Double entry in austrian cities

### ISSUE THREAD

**Issue by BerndKarlsboeck** [dr5hn/countries-states-cities-database#88]
Example in csv cities

3062,"Politischer Bezirk Zell am See",2061,5,15,AT,47.28333000,12.70000000
3874,"Zell am See",2061,5,15,AT,47.32556000,12.79444000

One entry says "politischer Bezirk"  which means "political district" and the other one doesn't.

Delete the entries that say "politischer Bezirk". in this case entry 3062 and keep 3874
This is only the case for some Austrian entries.

**Comment by dr5hn** [comment]
@BerndKarlsboeck Thanks for reporting. 🎉 Will fix it ASAP.

**Comment by dr5hn** [comment]
@BerndKarlsboeck Fixed in #96. Please verify.

**Comment by dr5hn** [comment]
@BerndKarlsboeck  Fixed. Hence closing.
