### ISSUE TITLE
Foreign Key error

### ISSUE THREAD

**Issue by lionsgatecreative** [dr5hn/countries-states-cities-database#887]
Attempting to execute the countries.sql file, but the following error is returned by phpMyAdmin:

#1005 - Can't create table `magelln_loc`.`countries` (errno: 150 "Foreign key constraint is incorrectly formed")

**Comment by lionsgatecreative** [comment]
Worked when I instead used world.sql.

**Comment by dr5hn** [comment]
@lionsgatecreative It appears the country data is linked to the states and cities tables. To import the country.sql file, you may need to temporarily disable foreign key checks.
