### ISSUE TITLE
Buenos Aires City Missing as State

### ISSUE THREAD

**Issue by kingbeto** [dr5hn/countries-states-cities-database#90]
Hi there. Great job by the way.

In Argentina we have the Buenos Aires Province and the Autonomous City Of Buenos Aires. Two completely different things. Autonomous City Of Buenos Aires is super big in population and economically speaking.

**Change 1: In States: Buenos Aires City is a city but also a Sate. It's name is Autonomous City Of Buenos Aires.**
In states: you can add this at the end:
    {
        "id": 4860,
        "name": "Autonomous City Of Buenos Aires",
        "country_id": 11,
        "country_code": "AR",
        "state_code": "C"
    }

**Change 2: In States: Replace this (the value that changed was the state code from C to B and the name from Buenos Aires to Buenos Aires Province):**
    {
        "id": 3656,
        "name": "Buenos Aires Province",
        "country_id": 11,
        "country_code": "AR",
        "state_code": "B"
    }

**Change 3: In Cities, all the cities you have from Buenos Aires Province are actually Buenos Aires City towns.** They are not cities, but We can consider them cities as they are huge and it's OK to do it. We, Argentinians, we do it all the time.

So You should change All _"state_id": 4860_  in the cities.json file to this _"state_id": 3656_ 
As you can see the state code remains the same.
BA city has state code C and BA Province has state code B.

You don't have BA Province cities in the database, unfortunately. That's another story.

THANKS A LOT AND GREAT JOB.

**Comment by dr5hn** [comment]
@kingbeto Thanks it helped you.

Thanks for reporting. 🎉 I will look into it ASAP.

**Comment by dr5hn** [comment]
@kingbeto Done. Please Verify. #102
