### ISSUE TITLE
Asturias - Spain

### ISSUE THREAD

**Issue by jgsaez9** [dr5hn/countries-states-cities-database#916]
I don't see any city for the province of Asturias in Spain.

Asturias State Data: {
  name: 'Asturias',
  isoCode: 'AS',
  countryCode: 'ES',
  latitude: '43.36139530',
  longitude: '-5.85932670'
}

Trying to get cities with exact ISO code: AS
Cities found: 0

**Comment by Aakash315** [comment]
![Screenshot-Asturias](https://github.com/user-attachments/assets/f35a2fd6-5f0b-4a34-9a4f-bde593013ee1)
