### ISSUE TITLE
Fix codes for Moldova - Floresti and Falesti

### ISSUE THREAD

**Issue by victorgoodleap** [dr5hn/countries-states-cities-database#924]
Official codes for `Floresti` is `FR` and for `Falesti` is `FL`.

**Comment by victorgoodleap** [comment]
I can create a PR but I'm getting an error when I try to clone the repo

**Comment by Aakash315** [comment]
![Screenshot 2024-12-16 173033](https://github.com/user-attachments/assets/683fd7bc-4e8b-4e9c-8c89-8fc1d0eef28d)

**Comment by Aakash315** [comment]
https://www.iso.org/obp/ui/#iso:code:3166:MD

**Comment by victorgoodleap** [comment]
@Aakash315 It's very wired. In the old standard, the car registration plates used two letters from the name of the city where the car was registered. There was FR for Floresti - https://platesmania.com/md/regionstat-FR, and FL for Falesti.
