### ISSUE TITLE
Missing City entries in Austria

### ISSUE THREAD

**Issue by TwentyFourMinutes** [dr5hn/countries-states-cities-database#95]
`Sankt Jakob im Rosental` is missing as a City entry in the State: `Kärnten`, `Austria`. See [Wikipedia](https://en.wikipedia.org/wiki/Sankt_Jakob_im_Rosental).

**Comment by dr5hn** [comment]
@TwentyFourMinutes Thanks for reporting. 🎉 

I will check it out.

**Comment by TwentyFourMinutes** [comment]
Also `Rohrbach in Österreich` merged with `Berg bei Rohrbach` and is now named `Rohrbach-Berg` see [Wikipedia](https://de.wikipedia.org/wiki/Rohrbach-Berg)

**Comment by dr5hn** [comment]
@TwentyFourMinutes Fixed in #96. Please verify.

**Comment by TwentyFourMinutes** [comment]
Seems to be alright now!

**Comment by dr5hn** [comment]
Thanks for verification. Hence closing it.
