### ISSUE TITLE
No world regions linked to countries

### ISSUE THREAD

**Issue by lesiagnapovska359** [dr5hn/countries-states-cities-database#98]
All the countries should be linked to region like Europe, Asia and so on.
Here are the API which provide regions for country https://restcountries.eu/rest/v2/all?fields=name;region

**Comment by dr5hn** [comment]
@lesiagnapovska359 
Wohoo.. 🎉  Nice One.. Thanks for sharing this.. 

This will make a good enhancement to database.
Really appreciate it. Will add it soon..

**Comment by lesiagnapovska359** [comment]
Wellcome! Many thanks to the database. It cames really helpfull for me.

**Comment by dereuromark** [comment]
Oh, I guess this is what I meant with https://github.com/dr5hn/countries-states-cities-database/issues/125 and continents
I did that already for 200 of 250 countries.
I guess your list is complete though?

**Comment by dereuromark** [comment]
{"name":"Turkey","region":"Asia"}
Shouldnt that be in the Europe region? Especially since even Russia is still mainly Europe :)
At least that's where I put them in my DB after some research on it.

**Comment by dr5hn** [comment]
@dereuromark According to Wikipedia, it should belong to Asia.

Check this 👇🏼 
Turkey, officially the Republic of Turkey is a transcontinental country located **mainly** on the Anatolian peninsula in **Western Asia**, with a **smaller portion** on the Balkan peninsula in **Southeastern Europe**.

It has a major portion in Asia and a smaller portion in Europe.

**Comment by dr5hn** [comment]
@lesiagnapovska359 Done. Added. #126
