### ISSUE TITLE
Kosovo bug

### ISSUE THREAD

**Issue by AvdiuAndin** [dr5hn/countries-states-cities-database#99]
Thanks for the time that it took to build this repo :) I really appreciate it
 
I just wanted to let you know that Kosovo is not under/part of Serbia.
Therefore, states with ids:
1. 3730
2. 3739
3. 3735
Should be removed and Kosovo should be inserted as a new Country

**Comment by dr5hn** [comment]
@AvdiuAndin Thanks for reporting. 🎉 

What about cities of Kosovo ? Did you got any resource, where i can find the info about Kosovo ?

**Comment by AvdiuAndin** [comment]
Wiki data: https://www.wikidata.org/wiki/Q1246
Cities: https://www.citypopulation.de/en/kosovo/cities/
Country code: https://countrycode.org/kosovo

INSERT INTO `countries` ( `name`, `iso3`, `iso2`, `phonecode`, `capital`, `currency`, `native`, `emoji`, `emojiU`, `flag`, `wikiDataId`) VALUES
('Kosovo', 'XKX', 'XK', '383', 'Prishtina', 'EUR', 'Kosova', '🇽🇰', 'U+1F1FD, U+1F1F0', 1, 'Q1246'),

**Comment by dr5hn** [comment]
@AvdiuAndin Awesome. Thank you so much. 🎉

**Comment by dr5hn** [comment]
@AvdiuAndin Done. Please Verify. #102
